### ISSUE TITLE
Feature: Provide a nice card overview for courses on the Dashboard

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#12]
While there are Moodle installations out there where teachers and students have a massive amount of courses and prefer list views of their courses, there are also Moodle installations where users a enrolled in just one or few courses. 

On these Moodle installations, the course list should be presented in an attractive and informative card overview on the Dashboard. Moodle core (in 3.x and 4.0) has the "card" course list layout, but other themes and solutions go beyond that.

This issue is a place to discuss the needs and to identify real pain points which could then be solved afterwards.

**Comment by sberger** [comment]
Some of our users have requested to use the course list only as a list without course images - regardless of the number of their own courses.

**Comment by abias** [comment]
After the latest internal discussion, I will close this issue.
The requested feature can be either realized with the advert tiles (as hardcoded course tiles) or with our companion plugin Dash Pro by bdecent (as dynamic my-courses grid).
