### ISSUE TITLE
Release tasks: Add a note that you can create child themes from Boost Union

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#122]
It would be worthwhile to add a note to README.md to highlight the fact that you can create child themes from Boost Union (which are then grandchild themes from Boost core). 

This way, you can benefit from Boost Union's features without losing the possibility to change any other theme functionality based on your local needs. This approach might be preferable than creating a direct child from Boost and copying features / code from Boost Union over to your own Boost child theme.

**Comment by lucaboesch** [comment]
Good Idea @abias.
That entry in README.md should then also in put in evidence what you have to do to run the Behat suite then to use your Boost Union child (which is a Boost grandchild) theme then.
In Boost Campus times I ran a Boost grandchild theme and I had to make provisions to have the full Behat suite run using that theme.

**Comment by ksteitz** [comment]
Thanks for picking up and formulating my idea adding a note for the possibiltity to use child- /grandchild-themes. As said before it would be nice to have it also at https://moodle.org/plugins/theme_boost_union 
I think it best fits following "The admin can enable and configure only the theme features he needs and does not need to care about side effects from other, disabled theme features." Someting like: 
"If you want to add local features or settings (that are not interesting as a pull request or feature request for all) you can create child themes from Boost Union, which are then grandchild themes from Boost core."

**Comment by abias** [comment]
I slightly modified your proposed text, Klaus, and added it to the README in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/commit/0a838a102e103e8f366ebab33b9abbb4d7a84fff as well as to the plugin description on https://moodle.org/plugins/theme_boost_union.

**Comment by ksteitz** [comment]
Thanks Alex!
