### ISSUE TITLE
Feature: Image area

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#125]
Boost Campus provided the `theme_boost_campus | imageareaitem*` settings which allowed admins to show images like sponsor badges at the end of each page.

I may be worthwhile to port this feature over to Boost Union. However, this has rather lower priority as you will be able to achieve the same goal with a text block and some more clicks as soon as #30 / #118 is integrated.

**Comment by wiebkemueller-hsh** [comment]
@abias @stefanscholz isn't this solved with the block areas? if yes, let's close it.

**Comment by wiebkemueller-hsh** [comment]
I'd like to close this :-)

**Comment by abias** [comment]
Well. Boost Campus had a _dedicated_ image are for icons / badges in the footer. But I agree that admins who want to have something like that in Boost Union as well can build with the footer and the footnote. Closing.
