### ISSUE TITLE
Feature: Improve usability of course management page

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#129]
In https://github.com/moodle-an-hochschulen/moodle-theme_boost_campus/issues/69, @stemiwe wrote for Boost Campus:

> We improved the usability of our course management page by 3 changes, I think it would be great to include them in boost_campus:
> 
> 1. adding the search courses box to the top of the management view
> 2. showing both short name and full name for a course in the course area
> 3. adding a direct link to the selected course to the course view area
> 
> ![managementview](https://user-images.githubusercontent.com/13886080/70710254-0e372080-1cdf-11ea-80d9-b466a2f039dd.png)
> 
> we accomplished this by changes in
> /course/management.php
> /course/classes/management_renderer.php
> /course/classes/management/helper.php
> /course/classes/list_element.php
> 
> in /course/management.php add this line before "echo $renderer->management_form_start();"
> 
> ```
> echo $renderer->course_search_form($search);
> ```
> 
> in /course/classes/management_renderer.php add a view button in the function search_listitem_actions:
> 
> ```
>        // View.
>        $actions[] = $this->output->action_icon(
>            new \moodle_url('/course/view.php', array('id' => $course->id)),
>            new \pix_icon('i/course', \get_string('view')),
>            null,
>            array('class' => 'action-view')
>        );
> ```
> 
> In /course/classes/management/helper.php add a view button in function get_course_listitem_actions:
> 
> ```
>        // View. 
>            $actions[] = array(
>            'url' => new \moodle_url('/course/view.php', array('id' => $course->id)),
>            'icon' => new \pix_icon('i/course', \get_string('view')),
>            'attributes' => array('class' => 'action-view')
>        );
> ```
> 
> In /course/classes/list_element.php change function get_formatted_name:
> 
> ```
> return format_string($this->__get('shortname'), true, $this->get_context()) . ' - ' . format_string($this->__get('fullname'), true, $this->get_context())
> ```

While the first item (the search box) is there now in Moodle 4.x, the second and the third proposals are still valid for Boost Union and it would be worthwhile to solve it.

**Comment by abias** [comment]
The second goal can be achieved with the Moodle core setting $CFG->courselistshortnames.

I will work on implementing the remaining third goal now.

**Comment by lucaboesch** [comment]
I think this change 'adding a direct link to the selected course to the course view area' would be great to include them in Moodle Core.
Please add an issue to https://tracker.moodle.org/, @stemiwe.
The more thing are handled by Boost Union, the more templates etc have to be taken over and maintained over time.
Just my 2¢

**Comment by stemiwe** [comment]
@lucaboesch im pretty sure i suggested that years ago, and kinda gave up on ever getting anything through to moodle core :)

but yeah, i ll try suggesting it again and have you guys vote on it :)

**Comment by lucaboesch** [comment]
I don't see any tracker issue yet regarding this topic
`Reporter in (technikum-wien) AND Project in (MDL)`
@stemiwe, were you able to create one?

**Comment by stemiwe** [comment]
@lucaboesch sorry, this got buried under other work.

I'm pretty sure I made at least a discussion on the forums back then - I created an MDL now - please vote on it and let's hope it gets implemented: https://tracker.moodle.org/browse/MDL-80237
