### ISSUE TITLE
Feature: Allow admins to change the course settings menu

### ISSUE THREAD

**Issue by christianwolters** [moodle-an-hochschulen/moodle-theme_boost_union#13]
Moodle 4 changes the way settings are accessed in the course. We need to discuss the new development in contrast to the convenient way boost campus has provided in course settings.

As short example case: accessing the enrolment settings table

In Boost Campus, one could enable a "super menu" with submenus directly clickable from everywhere

![image](https://user-images.githubusercontent.com/2005580/158842437-9896ce53-6fc3-4f73-ac7c-7cf61a228b9b.png)

In Boost 4, one has to 
- choose the category "Participants" (1)  which opens a new page
- select "Enrolment methods" via dropdown menu (2) to open the desired page

![image](https://user-images.githubusercontent.com/2005580/158842259-980e93ac-bb82-434d-9eed-a6331687c3f2.png)

While it probably would be straight forward to implement this feature, we have to discuss:

- if the boost_campus behavior is really the best way to navigate, or just the way we learned it the last year as boost_campus users
- if we such a divergence from core is necessary or if it would hurt this plugin in the future

**Comment by christianwolters** [comment]
Hi @lucaboesch,

if I'm not mistaken, you called this menu the "tertiary navigation" <- is this an official term used by Moodle?
(instead of "settings" menu)

**Comment by lucaboesch** [comment]
@christianwolters according to Mary Cooch and Helen Foster it's better to avoid such tech/dev speak terms like "tertiary navigation". 
Helen writes:

> We haven't come up with a good name yet, apart from saying the dropdown menu on the Participants page.

Best,
Luca

**Comment by ksteitz** [comment]
groups: just another example of a changed navigation way
In Moodle 4 core (Boost) the "groups"-features are somehow hidden and not intuitive to find: 
"Participants" -> drop-down "Enrolled Users" -> "Groups" 
A user thus has to know clicking "Enrolled Users" is the way using "Groups"-features.

**Comment by wiebkemueller-hsh** [comment]
The same happens for reimporting course content (more admin feature in our case, but still), you go via the more link in the secondary navigation than have to identify  "course reuse" as the correct term. But after a few months of using these "dropdowns underneath the menu"-tertiary menus, I have gotten used to it.

**Comment by wiebkemueller-hsh** [comment]
@christianwolters Could the smart menu functionality #300 be a solution for this, create menus with direct links for teacher e.g.? if yes, this could be closed.
