### ISSUE TITLE
Feature: Menu bar

### ISSUE THREAD

**Issue by stefanscholz** [moodle-an-hochschulen/moodle-theme_boost_union#136]
I think it would be great to have an additional menu bar, which the admin can use for various purposes to provide relevant information at a glance; a multi-purpose tool which is subtle but always available.

### User stories

As an administrator, I can

- enable a menu bar
- choose a location for the menu bar: top, bottom
- configure the positioning: fixed, static
- set the appearance (bgcolor, color)
- add a custom text and choose it’s position (possible as ticker)
- add links to the menu bar with label and/or icons
- add a quick jump menu with autocomplete for courses: idnumber or shortname or, fullname
- add a list of courses as dropdown menu from specific categories, with a specific custom course field where the current user has a specific role within a specific date range
- add a flavor switch (mainly for light/dark/auto, but could also be for accessibility or presentation)
- add a content width switch (full with blocks, full without blocks, normal)
- add indicators for due/overdue activities plus popover with information which ones
- add indicators for due/overdue assignments plus popover with information which ones
- add information about open timed quizzes plus popover with information which ones
- add information about events (ongoing and upcoming)
- add links as dropdown to dash dashboards the current user has access to

As a teacher, I can

- see and access my courses with one click from anywhere
- see and access courses from a specific category from anywhere
- see and access courses with a specific custom field from anywhere
- start typing the course’s idnumber or shortname in a search field, see which courses exist with relevant metadata and access it without using the mouse
- access the search field using a keyboard shortcut
- choose if a quiz should be added to the top bar (if the admin has allowed it)

As a student, I can 

- see and access my courses with one click from anywhere
- see and access courses from a specific category from anywhere
- see and access courses with a specific custom field from anywhere
- start typing the course’s idnumber or shortname in a search field, see which courses exist with relevant metadata and access it without using the mouse
- access the search field using a keyboard shortcut
- see if there are any due/overdue activities

also solves #93, #18, #10

**Comment by stefanscholz** [comment]
We started working on this issue as part of the implemtation of #137

**Comment by abias** [comment]
I think this issue can be considered as solved as #300 has been merged now.
