### ISSUE TITLE
Feature: Smart menus

### ISSUE THREAD

**Issue by stefanscholz** [moodle-an-hochschulen/moodle-theme_boost_union#137]
The horizontal main navigation is unfortunately rather static. I see huge potential just by making the menu customizable and dynamic (in the sense of that users only see what they are supposed to see). 

It should basically cover the same applications as Boost Navigation Fumbling, and a few additional ones.

The feature has been specified with the needs of academic institutions in mind, where the term is a key component for all things navigation and (course/category) architecture. It aims to implement a set of tools to provide easy access for users and powerful tools for administrators to manage it.

### User Stories

As an administrator, I can

- create a smart menu
- add a title for the smart menu
- set the appearance of the smart menu to “link list”, “cards” or “mega”
- if appearance is mega, I can add a description for the smart menu and add blocks
- add static menu items
- order the items
- add icons to the menu items
- add a smart menu to another (static) menu item
- define who sees the (smart) menu and menu item by role (any context or system context)
- define who sees the (smart) menu and menu item by cohort
- define who sees the (smart) menu and menu item by language
- define who sees the (smart) menu and menu item by capability required
- add all courses that the current user is enrolled to in specific categories with specific roles and specific completion statuses and in a specific date range (custom or past/current/future) and a specific course field
- add all courses in a specific category
- manage system main menu items (i.e. change order, show/hide or home, dashboard, my courses, site admin)
- add a smart menu to a block

As a user, I can

- see and access relevant links at any time
- navigate to any course with just two clicks (expand menu and then click) which is relevant for me

also solves #93, #65, #10, #9

**Comment by abias** [comment]
@stefanscholz has started the development of this feature :)

**Comment by ksteitz** [comment]
Thanks for that initiative! 
As we learned also today in the Moodle an Hochschulen developer-monthly, other universities, such as Uni Würzburg (https://github.com/uniwue-rz), Uni Wien (https://github.com/elearning-univie), TU Berlin (Martin Gauk, https://github.com/innocampus) worked at that topic and implemented similar pulldown-menus in Boost Union. Therefore https://github.com/MartinGauk has got the task to organize a meeting between these people with @stefanscholz to find synergies and avoid or at least minimize double development.

**Comment by danowar2k** [comment]
Interesting. The mockup restricts appearance of dynamic items to roles and not capabilities, which would me more Moodle standard, I think. Why your decision regarding this?

**Comment by abias** [comment]
> Interesting. The mockup restricts appearance of dynamic items to roles and not capabilities, which would be more Moodle standard, I think. Why your decision regarding this?

@danowar2k - I think the answer is: The concept of restricting menu items to roles is easier than restricting them to capabilities. Please give it a try and raise any improvement proposals if you like.

**Comment by abias** [comment]
This issue is solved now as #300 has been merged.
