### ISSUE TITLE
Improvement: Get rid of runs-on: ubuntu-18.04 in Github workflow yml

### ISSUE THREAD

**Issue by lucaboesch** [moodle-an-hochschulen/moodle-theme_boost_union#145]
Beginning 01.12.2022 no workflows will be done any more with ubuntu-18.04 machines since it's about to be deprecated and removed, see https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22

**Comment by abias** [comment]
Thanks, Luca.

This is basically a subset of the Call-to-actions in the recent releases of moodle-plugin-ci (see https://moodlehq.github.io/moodle-plugin-ci/CHANGELOG.html)

I plan to update the GHA config in all plugins of the Moodle an Hochschulen association quite soon to solve this requirement.

Looking at https://github.com/actions/runner-images/issues/6002, I understand why some GHA jobs didn't run yesterday as planned :)
However, I do not understand the announcement in a way that december/2022 is a hard deadline - I understand that the deadline is april/2023.

**Comment by abias** [comment]
PS: What I wanted to say is - please allow me to change GHA in a coordinated step for all plugins, do not change the GHA configuration for Boost Union yourself.

**Comment by abias** [comment]
This is done now in 44a47e6784104857078068ce02c2d6d2c47d71d3
