### ISSUE TITLE
Feature: Add 'contact' and 'help' and 'maintenance' static pages

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#150]
Boost Union already supports a 'imprint' static page which can be filled by admins.
Similar to this solution, it would be nice if we would have additional prepared static pages which can be easily filled by admins:

* Contact - for contact information (this should not necessarily replace the support form which can be controlled on /admin/settings.php?section=supportcontact)
* Help - for help information and FAQs
* Maintenance - for background information about planned downtimes

**Comment by christianwolters** [comment]
Will be part of next release, available as unreleased on main branch.
