### ISSUE TITLE
Feature: a real favicon allows to make icons on mobile desktops

### ISSUE THREAD

**Issue by ralf-krause** [moodle-an-hochschulen/moodle-theme_boost_union#151]
With the release of Moodle 4.1 the favicon is an upload area for a logo. Yes, the logo is shown in le left corner of the browser tab but that's all.

A real favicon allows to make icons on mobile desktops. To see the difference please go to the site https://bildungsportal.magdeburg.de/moodle/ . It's still a site with Moodle 3.11.11. Open this site on a smartphone or a tablet. Open the share menu. Choose the item "To the home screen" and save the favicon "Bildungsportal" on the home screen.

The favicon on the Bildungsportal site is a set of different images made by the Stadtmarketing Magdeburg. I linked the images in the setting additionalhtmlhead. You can look into the source code and search for "favicon". Yes, the favicon should get a small white border around but they set a copyright for the favicon and the other marketing images, So I let the icons on the Magdeburg server and linked them only.

There is a second demo site which you already can see on my iPhone home screen. Go to https://moodle.bildung-lsa.de/gs-dahlenwarsleben/ on your smartphone. Open the share menu and save the favicon "Dahlenwarsleben" on your home screen. I made the images with a favicon online generator, uploaded the images to a front page folder and linked them in the setting additionalhtmlhead. You can look into the source code and search for "favicon".

Try the same process with any Moodle website which uses the favicon feature from Boost Campus, Boost Union or from the current Moodle 4.1 release.

![iphone-share-to-home-screen](https://user-images.githubusercontent.com/27956839/204296409-6d8abbaf-b957-467c-b658-07239871b8c1.jpeg)
![iphone-icon on home-screen](https://user-images.githubusercontent.com/27956839/204296597-6cab94ff-f4d2-4e8c-8195-06af986cf3ee.png)

**Comment by ralf-krause** [comment]
Please look on the site https://herwig.de/anleitungen/vuepress/manifest.json.html#favicons-und-app-icons-erstellen

**Comment by abias** [comment]
The support for iOS devices was added in #206, the improved support for Android devices was postposed to #511
