### ISSUE TITLE
Improvement: Allow overriding of brand colors in flavours

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#155]
This is a follow-up to #153:

In the first implementation of the flavours feature, it is not possible yet to override the brand color within a flavour.

It would be worthwhile to extend this in a way that also SCSS code can be used.
The challenge is to build this in a way that the brand color is properly compiled in the shipped CSS and that we do not end up with a blown up CSS result which just overrides all colors in every single selector from Boost Union's main SCSS.

To achieve this goal, a closer look at https://tracker.moodle.org/browse/MDL-65438 and https://github.com/bmbrands/theme_picture/compare/change_css_urls (which was the basis for a similar feature in Moodle workplace) should be the way to go.

**Comment by mwehr** [comment]
Hi, 

Anyone working this? 
If not I will start working in this.

regards
Mario

**Comment by abias** [comment]
Hi @mwehr ,

I am not aware that anyone is working on this yet. I would really appreciate if you would have a look at it and will add you as assignee.

Don't hesitate to drop us a line if you have questions about the implementation details.

Cheers,
Alex
