### ISSUE TITLE
Feature: Add advertisement tiles to the frontpage

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#161]
For first-time visitors, Moodle sites are quite boring and uninformative. If I, as site manager, want to provide some information to first-time visitors, I will most likely want to add this to the frontpage. However, there are only inferior tools in Moodle for managing content on the frontpage. 

As a site manager, I want to overcome these limitations and want to be able to add advertisement tiles to the frontpage:
* I want to be able to define up to 12 advertisement tiles
* Advertisement tiles can either
-> link to a particular course
-> link to a particular course category
-> link to a particular (internal or external URL)
* For each tile, I have
-> a plain text input setting for the tile's title (which may remain empty)
-> a rich text editor setting for the tile's content (which may remain empty)
-> an upload setting for the tile's background image (which may remain empty)
-> a setting for the link target (a course, a category, a URL - which may remain empty)
-> a setting for the link title (which may remain empty if no link target is set)
* I want to be able to configure if the tiles will be shown as 1 column, 2 column, 3 column or 4 column grid
* The tiles should be shown on the frontpage and I want to be able to configure if they should be shown before, after or instead of the frontpage content
* The tiles should come with a simple layout which fits into Boost's look (i.e. no drop shadows, gradients or something like that)

**Comment by lucaboesch** [comment]
Closed by #167.
