### ISSUE TITLE
Feature: Add a slider to the frontpage

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#162]
For first-time visitors, Moodle sites are quite boring and uninformative. If I, as site manager, want to provide some information to first-time visitors, I will most likely want to add this to the frontpage. However, there are only inferior tools in Moodle for managing content on the frontpage. 

As a site manager, I want to overcome these limitations and want to be able to add a slider to the frontpage:
* I want to be able to define up to 6 slides in the slider
* A slide can either
 * link to a particular course
 * link to a particular course category
 * link to a particular (internal or external URL)
* For each slide, I have
 * a plain text input setting for the slide's title (which may remain empty)
 * a rich text editor setting for the slide's content (which may remain empty)
 * an upload setting for the slide's background image (which may remain empty)
 * a setting for the link target (a course, a category, a URL - which may remain empty)
 * a setting for the link title (which may remain empty if no link target is set)
* If the slider will be based on Bootstrap carousels, I want to be able to configure the slider's behaviour details
* The slider should be shown on the frontpage and I want to be able to configure if it should be shown before, after or instead of the frontpage content
* The slider should come with a simple layout which fits into Boost's look (i.e. no drop shadows, gradients or something like that)

**Comment by kaaermes** [comment]
that's exactly the function I'm looking for our moodle here at Friedrich-Schiller-University Jena; it's very useful for announcing events, new features and stuff like that

**Comment by slaudel** [comment]
We also would like to see this feature in boost union, when we will abandon using theme adaptable in favour of boost union.

**Comment by abias** [comment]
This was solved in #523

**Comment by slaudel** [comment]
Will the slider functionality be backported to older branches like MOODLE_401_STABLE or will it only be available to Moodle 4.3 and newer?

**Comment by abias** [comment]
Hi @slaudel ,

thanks for asking.

If you look at https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/tree/master#moodle-release-support, you will read there: "This plugin is only maintained for the most recent major release of Moodle as well as the most recent LTS release of Moodle. Bugfixes are backported to the LTS release. However, new features and improvements are not necessarily backported to the LTS release.". This is the baseline for all plugins of our association.

However, as it stands currently, Boost Union gets some kind of "extended release support". Which means that normally we backport all unreleased changes to 4.2 and 4.1 currently as well when an official release if pushed out.

Please expect the next release for 4.1 - including the slider - presumably next week.

Cheers,
Alex

**Comment by slaudel** [comment]
Hi @abias,

thanks for the clarification. Then we will patiently wait for the 4.1 release of the slider. :star_struck: :clap:

**Comment by abias** [comment]
@slaudel , here you go:
The feature has been backported to 4.1 and the new release has been tagged now. Github actions will push it to moodle.org/plugins as well soon.
