### ISSUE TITLE
Feature: Mark broken links

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#163]
Moodle has an internal check mechanism which changes links to brokenfile.php if a link is detected to be broken.
See https://github.com/moodle/moodle/blob/1d863c338ac6ace8e6b945f0e2c49753acfdb837/lib/weblib.php#L1342 and https://github.com/moodle/moodle/blob/7c3188b2ca754a3842cb4b1e0a145163c1595f59/lib/filelib.php#L455.

In Boost Campus, these links were highlighted this way:

```
/* Mark broken links with red color. */
a[href*="/brokenfile.php"] {
    color: $danger;
}

/* Add Font Awesome "broken chain" icon in front of broken link. */
a[href*="/brokenfile.php"]::before {
    font-family: FontAwesome;
    content: "\f127" !important;
    padding-right: 10px;
}
```

It would be worthwhile to add an admin setting which adds this CSS snippet again.

**Comment by lucaboesch** [comment]
Closed by #512.
