### ISSUE TITLE
Feature: Mark mailto links

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#164]
As you know, links do not necessarily go the HTTP pages, you can also link to email addresses with the mailto: handler. However, users do not know that a link is an email link until they click it.

In Boost Campus, these links were highlighted this way:

```
/* Add Font Awesome "email" icon in front of mailto links. */
a[href^="mailto"]::before {
    font-family: FontAwesome;
    content: "\f003";
    padding-right: 5px;
}
```

It would be worthwhile to add an admin setting which adds this CSS snippet again.

**Comment by lucaboesch** [comment]
Closed by #512.
