### ISSUE TITLE
Feature: Support H5P branding (for mod_h5p)

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#166]
Since Moodle 3.10, Moodle core provides a possibility to add branding to H5P modules. This was integrated in https://tracker.moodle.org/browse/MDL-69087 and is documented on https://docs.moodle.org/dev/H5P_styles. An example seems to be available on https://github.com/sarjona/h5pmods-moodle-plugin.

It would be worthwhile to evaluate if there is anything we could add to Boost Union to leverage H5P branding in the theme.

**Comment by abias** [comment]
This was solved in #210

**Comment by lucaboesch** [comment]
https://tracker.moodle.org/browse/MDL-79802 could potentially influence this in Moodle ≥ 4.4
