### ISSUE TITLE
Improvement: Reduce the amount of filearea calls for advertisement files

### ISSUE THREAD

**Issue by NinaHerrmann** [moodle-an-hochschulen/moodle-theme_boost_union#168]
Originally, the same file area for all background images should be used. However, ids in getting images stored by themes are hardcoded to 0 (https://github.com/moodle/moodle/blob/c3c3a1fe0fa0a35ffc1d47ee7c992d7363efec1d/lib/outputlib.php#L2062, 7.12.2022). 

Therefore, it was switched to fileareas which are indexed by the number of the tile (`tilebackgroundimg_x_`).  `get_area_files` is called 12 times - https://github.com/NinaHerrmann/moodle-theme_boost_union/blob/cd99307aa84099df348bcdae7b97f3def08efd4e/locallib.php#L562. This might be a performance issue, need to be tested.

**Comment by abias** [comment]
Note: This is a follow-up issue of #167 / #161

**Comment by christianwolters** [comment]
Hi,

does anyone know, if this is a real performance issue? In contrast to the many calls already made, one can argue both ways:
it doesn't really matter or each call is one to many... either way:
what would the right way to benachmark this? (method as well as criteria for improvement?)

When improvements are necessary, what would be good approaches to solve this?

some ideas:
- no code improvement here but caching of urls?
- move management of ad-tiles to an external admin settings page to have full control of the fileareas?

Cheers
Christian

**Comment by abias** [comment]
During my review of the (soon-to-be-merged) PR #167, I have simplified @NinaHerrmann 's code for getting the background images from the filearea(s). So, this issue breaks down to what is generally documented in #177.

Let's continue there.
