### ISSUE TITLE
Feature: Allow right-side blocks drawer of the home-page to be extended by default

### ISSUE THREAD

**Issue by ShUl0w** [moodle-an-hochschulen/moodle-theme_boost_union#169]
Currently, the right-side blocks drawer is always hidden by default. Especially in cases where the right-side blocks drawer is used to convey additional information, first time visitors/users (who may not even be logged in) may not be aware of the right-side blocks drawer even existing at all and therefore miss out on said information.

As a site manager, it would be useful to:

- Have the option to extend the right-side blocks drawer by default for users that are not logged in / log in for the first time

However, it should still be possible to keep the drawer in its last state as toggled by a logged in user (which it currently is).

**Comment by abias** [comment]
I would like to support this issue and have just some small comments:
* From my point of view, it would be useful to distinguish between the drawer state a) who visit the site for the first time (and are not logged in yet) and b) who have logged in for the first time. Admins should be able to control both behaviours separately.
* As soon as a user has logged in for the first time and the configured default behaviour has been used, the drawer should fall back to Boost Core's behaviour and just keep the state (open / closed) how the user left it.
* My gut feeling would be that this configuration could be placed in the "Appearance -> Boost Union -> Feel -> Blocks" settings tab for now and should be a new section heading "Right-hand block drawer". In #118, there will come some more settings for blocks and we might rearrange the block settings then some more.
* If you prepare a PR for this issue, please have a look at our checklist https://github.com/moodle-an-hochschulen/moodle-plugin-maintaining/wiki/Check-list-for-peer-reviewing-patches-and-pull-requests to build is as complete as possible.

Cheers,
Alex

**Comment by ShUl0w** [comment]
This has been successfully integrated in #230, closing.
