### ISSUE TITLE
Feature: Make course section "navigatable"

### ISSUE THREAD

**Issue by wiebkemueller-hsh** [moodle-an-hochschulen/moodle-theme_boost_union#17]
Navigation-wise Boost 4.0 got rid of everything above course level (left-hand navigation, breadcrumb). Maybe related to this - it seems impossible to link to individual course sections. 

We used this frequently in order to point users to specifics topics directly via link, so I think it would still be helpful to keep sections links, even if the breadcrumb and navigation do not support this level.

Or again - let this decision be part of the configuration? 

Add section level to Breadcrumb.
![breadcrumb](https://user-images.githubusercontent.com/72548805/159012427-1d77dfcd-a211-4f30-916d-0cbbfc368d29.png)

**Comment by wiebkemueller-hsh** [comment]
I just found that this might be a general setting, under 3.11 this was the case

admin/settings.php?section=navigation
"linkcoursesections"

**Comment by lucaboesch** [comment]
I think this is going to be fixed by https://tracker.moodle.org/browse/MDL-73556, Wiebke.

**Comment by lucaboesch** [comment]
@wiebkemueller-hsh I think you now can fulfill your requrement on a vanilla Moodle 4.0 Boost, since [https://tracker.moodle.org/browse/MDL-73556](https://tracker.moodle.org/browse/MDL-73556) has been taken in.
Could you maybe verify on [https://qa.moodledemo.net](https://qa.moodledemo.net)?
If so, this issue can be closed.

Best,
Luca

**Comment by wiebkemueller-hsh** [comment]
I am sorry for taking so long. It is not fixed yet in the way I thought it would work best (as with boost campus).

**Comment by wiebkemueller-hsh** [comment]
@lucaboesch I actually think https://tracker.moodle.org/browse/MDL-76225 will fix the problem.
