### ISSUE TITLE
Font size in textarea

### ISSUE THREAD

**Issue by giselebrugger** [moodle-an-hochschulen/moodle-theme_boost_union#172]
I tried to find out but without success what could be changing the font size using TinyMCE HTML editor (legacy) and moodle4.1 -Build: 20221128
see the two images
With theme boost: [https://tinyurl.com/2h6llz4v ] https://tinyurl.com/2h6llz4v
With teheme boost_union: [https://tinyurl.com/2hbwpuq9 ](https://tinyurl.com/2hbwpuq9)

**Comment by giselebrugger** [comment]
problem solved. It was the confusion with the two editors named tinymce html (old) and tinymce(new)
![editorcorreto](https://user-images.githubusercontent.com/5620195/207988276-e4bae454-9278-448a-997a-cd1d73806b60.png)
![Avisos](https://user-images.githubusercontent.com/5620195/207988315-4c90bc4b-a141-4d57-98c9-908337965141.png)

**Comment by lucaboesch** [comment]
Thanks for the info, @giselebrugger
