### ISSUE TITLE
Feature: Primary Navigation tweaks and Custom menu with audience targeting, via cohort membership

### ISSUE THREAD

**Issue by cjbsdigitallearning** [moodle-an-hochschulen/moodle-theme_boost_union#185]
Probably a big ask, but could you consider including some features to allow the primary navigation to be tweaked. As it stands I've hidden the 'Home' and 'My Courses' buttons via css, which was easy enough, but might be good to include option like these as I'm sure it would benefit a lot of users.

Second related suggestion would be some form of advanced custom menu. The standard custom menu item option with the standard Theme setting is super limited.  Key thing I'd want would be audience targeting, so menu items can be shown only to specific groups of users, probably via cohort membership for flexibility.

Have been using Boost Navigation Fumbling for a long time in pre-4, and it had some great features, like FontAwesome icons, and very advanced targeting. https://moodle.org/plugins/local_boostnavigation.  Something similar, but simpler built into Boost Union, would be an amazing feature .

I'm sure you would make a great job of these kinds of features and it would create an almost perfect alternative to Stock Boost in Moodle 4x for a lot of users.

Thank for giving it your consideration.
Neil

**Comment by wiebkemueller-hsh** [comment]
Hi @cjbsdigitallearning, have you had a look at the issues #136 and #137 yet? That's currently in the making and should be available in a not so far future. Regards, Wiebke

**Comment by wiebkemueller-hsh** [comment]
Hi Neil @cjbsdigitallearning 

since the smart menu features (incl. audience targeting via cohorts) are implemented we kindly ask you to use these functionalities. I will close this issue now.

Regards
Wiebke
