### ISSUE TITLE
Bugfix: Back to top is over help in Database activity

### ISSUE THREAD

**Issue by noisyjerm** [moodle-an-hochschulen/moodle-theme_boost_union#186]
The database activity in Moodle 4.1 introduces a footer. This shifts the core help icon up and under the Back to top

![image](https://user-images.githubusercontent.com/436184/211949131-52185493-a157-440e-8d90-75529afb7610.png)

Fortunately a class has been added to the body which can be used to fix this. The following SCSS can be added to /scss/boost_union/post.scss

body.hasstickyfooter #back-to-top {
    bottom: 5rem;
    @include media-breakpoint-up(sm) {
        bottom: 9rem;
    }
}

**Comment by abias** [comment]
Thank you very much @noisyjerm for this heads-up!
You proposed CSS was spot-on and worked fine in my tests.

I have added to CSS code to the 4.1 upgrade branch in [968adcc](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/commit/968adcc9ead93d5268dc3f737a6cd7ca0749d6de), the fix will be included in the 4.1 release which will be published quite soon!

Cheers,
Alex
