### ISSUE TITLE
Improvement: Add "collapse all" and "expand all" links to the course index drawer

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#187]
Up to now, the items in the course index drawer are expanded by default when the drawer is opened for the first time in a particular course. In long courses, this can be quite overwhelming for some users.

While the main course page has "collapse all" and "expand all" links which help the users to close / re-open all sections with one click, the course index drawer lacks this feature.

It would be great to add this feature to the course index drawer as well, but we have to take care that the usability of the drawer is not harmed by this additional link.

**Comment by lucaboesch** [comment]
See also https://tracker.moodle.org/browse/MDL-76891

**Comment by wiebkemueller-hsh** [comment]
see also [https://tracker.moodle.org/browse/MDL-71212](https://tracker.moodle.org/browse/MDL-71212)

James Calder has mentionend a technical challenge in both trackers, but IMHO I would suggest this is a UX first issue, and then the technical realisation would have to be adapted? Not knowing what this would involve though.

> The list of collapsed sections and collapsed course index items is stored in a limited-width field (the value field in the table mdl_user_preferences, which is 1333 chars).  If too many sections and/or course index items are collapsed, an error occurs.  If section IDs are 7 digits, collapsing all sections and course index items would cause an error in a course of 80 sections, I think.  Having a collapse all option on course index items, in addition to the one on sections, would make this error more common.  This is related to [MDL-46739](https://tracker.moodle.org/browse/MDL-46739).

Maybe a limit to 79 course sections would do UX a favor, too?

**Comment by abias** [comment]
As MDL-71212 has landed in Moodle core in 4.3 now and is working automatically in Boost Union as well, I think this issue can be closed.
