### ISSUE TITLE
Scrollspy return to place on edit toggle

### ISSUE THREAD

**Issue by dbnschools** [moodle-an-hochschulen/moodle-theme_boost_union#19]
In the Fordson theme we had a scroll spy solution so that when the user turned editing on and the page refreshed, they were returned to the exact place on the page.  You could be at the bottom of a long scroll and when you clicked the edit button it would return you to the nearest topic div.  I should note that Fordson has always had the edit button in the top sticky menu ready for the teacher to use it.

This is one feature that any teacher who has been any other theme notices and appreciates right away.  It saves so much time and frustration with scrolling up and down.  Turn edit on and you are returned to the place you were working on the page.

**Comment by abias** [comment]
@t-schroeder - As discussed in the HU Forums, I have added you as assignee to this issue.

However, please note that [ShUl0w](https://github.com/ShUl0w) mentioned recently that he is also interested to handle this issue. Maybe you want to collaborate.

**Comment by JayBraker** [comment]
I implemented scrollspy very closely to afore mentioned theme fordson:
https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/57
PR includes basic testing instructions/gherkin scenarios.
