### ISSUE TITLE
Updated version of theme for Moodle 4.1

### ISSUE THREAD

**Issue by vinee2312** [moodle-an-hochschulen/moodle-theme_boost_union#196]
When can we expect an updated version of the theme to be released for Moodle 4.1

**Comment by abias** [comment]
Thanks for asking @vinee2312 .

Up to now, we know only of a minor issue of Boost Union on Moodle 4.1 and have, on the other hand, received several feedbacks that it works quite fine.

Regarding the official 4.1 release, we have started the upgrade process and would expect to release the release in about 2 weeks.

The upgrade is managed in #199
