### ISSUE TITLE
Upgrade: Upgrade the plugin to Moodle 4.1

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#199]
Moodle 4.1 LTS has been out for a while now. This issue is created to manage the upgrade process.

**Comment by abias** [comment]
A new upgrade-401 branch has been cut and pushed to https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/tree/upgrade-401. The upgraded version will be built and tested there.

**Comment by abias** [comment]
The existing Behat tests just had to be fixed in one tiny aspect (the cohort management page had changed) and are passing now.

**Comment by lucaboesch** [comment]
Stubs created.
Feel free to populate: https://docs.moodle.org/400/en/Boost_Union_theme https://docs.moodle.org/401/en/Boost_Union_theme

**Comment by abias** [comment]
The last changes have been applied to the upgrade-401 branch and my manual testing on 4.1 didn't reveal any major issues.

So I have now released Boost Union for Moodle 4.1 :)
