### ISSUE TITLE
Feature: Allow the admin to adapt the H5P width

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#201]
In scss/moodle/variables.scss, there is the variable `$h5p-content-maxwidth: 960px !default;`.
Similar to the variable `$course-content-maxwidth` which can already be customized in Boost Union, it would be great to allow the admin to customize the H5P width

**Comment by ralf-krause** [comment]
Great idea! 
I use it in some of my administrated platforms.

**Comment by lucaboesch** [comment]
Since #202 has merely fixed the H5P width within content bank, I would pledge to leave this open.

**Comment by abias** [comment]
@lucaboesch , I basically agree with you that this issue is not fully solved yet. However, it was just created as I spotted the existing SCSS variable and wanted to add a setting for it. I do not feel a reel need to control the H5P activity width separately from all other activities.

I rather think that the remaining aspect of this issue is now a subset of #18 and could be handled there. What do you think?

**Comment by abias** [comment]
I dare to close this now based on my comment above.
