### ISSUE TITLE
Simplification of some text strings

### ISSUE THREAD

**Issue by ralf-krause** [moodle-an-hochschulen/moodle-theme_boost_union#203]
Do we really need the addition no. for the number of info banners and the number of marketing tiles?

The text strings will be shorter without "no. " and they send the same information. Everyone who reads the text will understand this. If we use "info banner {$a->no}" instead of "info banner no. {$a->no}" the users will see "info banner 1" and "info banner 2" and so on. The addition "no. " is not needed.

There are 42 text strings containing "no. {$a->no}".  And the plugin uses the text strings for the settings of 5 info banners and 12 marketing tiles. Moodle also doesn‘t use "topic no. 5".

**Comment by abias** [comment]
Thank you, Ralf,

when we built these features, it seemed like a good idea to add "no." in front of the number. But I think you are right, we don't need that.

So I would agree to remove "no". from the setting labels, it's just that someone would have to build the PR now :)

I will label this as "good first issue", maybe someone from the community wants to solve this.

Cheers,
Alex

**Comment by abias** [comment]
This was solved in #220
