### ISSUE TITLE
Improvement: Allow flexible width for dropdown-items in more-section of course navigation

### ISSUE THREAD

**Issue by wiebkemueller-hsh** [moodle-an-hochschulen/moodle-theme_boost_union#231]
Different lenghts of the dropdown-items in the "more"-section of the course menu lead to linebreaks where there shouldn't be line breaks, in our testsystem (Moodle 4.1.1 with Boost Union 4.1.r.2. )

Using the dev-tools in the browser we found out that overflow-wrap and white-space are responsible for this.

![dev_tools_broken](https://user-images.githubusercontent.com/72548805/221869875-421782c1-1309-4554-9f1f-c101b7e8e8bc.png)

![dev_tools_repaired](https://user-images.githubusercontent.com/72548805/221869899-d70a08df-92c7-40e4-9113-ad93adea1157.png)

However, we tested this on the qa-moodle site (https://qa.moodledemo.net) running Moodle 4.2 where the menu displays the items correctly without the line breaks. Here, the white space attribute has a different value nowrap, the others aren't in use.

![qa_whitespace_no-wrap](https://user-images.githubusercontent.com/72548805/221871461-947b494f-ce89-4af3-8853-1c61b7baf95b.png)

My question is: Is this a behaviour the boost union theme should pick up or is this merely related to core?

BR
Wiebke

**Comment by lucaboesch** [comment]
Liebe Wiebke, das ist kein Boost-Union-Bug sondern direkt ein Moodle Core issue: https://tracker.moodle.org/browse/MDL-76947

**Comment by wiebkemueller-hsh** [comment]
Thank you! I did try to find related issues in the moodle tracker, but apparently used the wrong keywords in my search to find this one...

**Comment by lucaboesch** [comment]
[MDL-76947](https://tracker.moodle.org/browse/MDL-76947) is now in the newest releases.
