### ISSUE TITLE
Navbar colour settings - light font colour makes the search close cross invisible

### ISSUE THREAD

**Issue by james-pearce-bath-ac** [moodle-an-hochschulen/moodle-theme_boost_union#234]
The new navbar colour settings have added functionality that has been requested by several people in our institution and is very welcome thanks.

I have noticed when the navbar setting is set to a light font either with default dark background or primary colour there are a couple of issues with the search bar. 

1. The search close icon is picking up the css for icons to display using the light font colour option. This make the close icon impossible to view with those settings. This presents accessibility issues for use.   
![Search-bar-light-font issue](https://user-images.githubusercontent.com/61325278/223093899-862aa2ea-9292-441c-ac65-6583a6ca55ae.png)
2. Less critical the search bar background is white, see image attached. I would expect it to be using the background colour set in settings either the default colour or the primary colour. This might not be true of all users and the functionality of the search bar isn't affected so wouldn't be a priority compared to the above issue.

**Comment by abias** [comment]
Hi @james-pearce-bath-ac ,

many thanks for highlighting this issue.

I have to admit that I forgot the search panel when I reviewed and extended the dark navbar PR.

I will fix this and submit a PR quite soon.

**Comment by abias** [comment]
@james-pearce-bath-ac - I have created a PR on https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/237.

If you have any chance, please give it a test-drive to see if I forgot any glitch which you have spotted.

**Comment by abias** [comment]
#237 was merged now -> Closing.
