### ISSUE TITLE
Navbar colour setting - Edit mode indicator

### ISSUE THREAD

**Issue by james-pearce-bath-ac** [moodle-an-hochschulen/moodle-theme_boost_union#235]
With the nagar colour options set to 'Primary color navbar with light font color' the edit mode indicator isn't very clear when set to on. The 'on' state uses the same primary colour as the colour to be used for the navbar background and so it isn't obvious that the edit mode is on.

**Example images below, our primary colour is a dark blue.**
Edit mode off
![edit-mode-off](https://user-images.githubusercontent.com/61325278/223095909-ef1a021c-00d6-4975-927d-c3a5fb17119e.png)
Edit mode on
![edit-mode-on](https://user-images.githubusercontent.com/61325278/223095914-75c14016-e669-4c62-9038-fb134aea1766.png)

Maybe adding a setting for the edit mode setting on background colour could resolve this issue and may be useful when not using Navbar colours as the setting could be used to specifically highlight the edit mode as a potential warning to users.

This issue isn't particularly critical but may offer some accessibility improvements.

**Comment by abias** [comment]
Hi @james-pearce-bath-ac ,

many thanks for highlighting this issue.

In Moodle core, the edit switch uses the brand color as background color as soon as it is activated:
![grafik](https://user-images.githubusercontent.com/1092118/223180436-3c4cd86d-234c-46e0-8e4b-ca86d769809f.png)
![grafik](https://user-images.githubusercontent.com/1092118/223180474-a08a39f1-1e84-44d4-8b1b-76c194d584da.png)

We already made some small modifications to the edit switch within the dark navbar patch, but I have to admit that it was focused on the dark (grey) navbar and not the brand color navbar and it might have been too short-sighted.

I think for now we should just remove the brand color background from the edit switch on dark navbars:
![grafik](https://user-images.githubusercontent.com/1092118/223182063-289632a6-8ac6-4282-a82b-7eb0ebfe7ee2.png)
![grafik](https://user-images.githubusercontent.com/1092118/223182985-dd2411bc-8d4c-4008-9bca-670189950f5c.png)

![grafik](https://user-images.githubusercontent.com/1092118/223183146-4372f167-b23d-4436-9af9-934d70bc561b.png)
![grafik](https://user-images.githubusercontent.com/1092118/223183105-f88f9899-7da9-4048-ad62-fb7b8984bace.png)

![grafik](https://user-images.githubusercontent.com/1092118/223183352-b416aa2b-c8aa-4296-bd37-4622a6a221e4.png)
![grafik](https://user-images.githubusercontent.com/1092118/223184228-58f0b873-d8de-4895-bcf1-921ac1eca4f1.png)

That way, we will loose the highlight effect of the edit switch when editing is on, but it will be better as it is now anyway.

I will set up a PR for this fix soon.

**Comment by abias** [comment]
@james-pearce-bath-ac - I have created a PR on https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/237.

If you have any chance, please give it a test-drive to see if I forgot any glitch which you have spotted.

**Comment by abias** [comment]
#237 was merged now -> Closing.
