### ISSUE TITLE
Navbar colour settings light font hover issue

### ISSUE THREAD

**Issue by james-pearce-bath-ac** [moodle-an-hochschulen/moodle-theme_boost_union#236]
When the navbar colour is set to 'Primary color navbar with light font color' any dropdown menu items that are added via the 'Custom menu items' in the 'Theme settings' the text of the link when hovered stays as the light font colour rather than a contrasting dark colour, this would likely provide accessibility issues. Direct link hover states work as expected.

Navbar dropdown links before hover
![Brand-color-navbar-light-font-before-hover](https://user-images.githubusercontent.com/61325278/223100660-c8641750-6391-4ce9-af6f-eaca1a72ea03.png)

Navbar dropdown links when in hover state
![Brand-color-navbar-light-font-hover-issue](https://user-images.githubusercontent.com/61325278/223100541-4f12d64c-a089-4894-8489-078af1fc57c3.png)

**Comment by abias** [comment]
Hi @james-pearce-bath-ac ,

many thanks for highlighting this issue.

I have to admit that I forgot the custom menu when I reviewed and extended the dark navbar PR.

I will fix this and submit a PR quite soon.

**Comment by abias** [comment]
@james-pearce-bath-ac - I have created a PR on https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/237.

If you have any chance, please give it a test-drive to see if I forgot any glitch which you have spotted.

**Comment by abias** [comment]
#237 was merged now -> Closing.
