### ISSUE TITLE
Bug: Footer placement in different templates

### ISSUE THREAD

**Issue by JayBraker** [moodle-an-hochschulen/moodle-theme_boost_union#241]
Hi,

I came across something odd while styling a custom page:

Placement of the footer elements is not consistent across columns and drawers template:
[drawers.mustache](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/master/templates/drawers.mustache#L186-L189)
[columns2.mustache](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/master/templates/columns2.mustache#L113-L115)

The prior places the footer inside the page container, but the latter places it inside the page-wrapper container.

This led to some confusion an I would hope for a consistent page structure.

Was the decision made deliberately?

**Comment by abias** [comment]
Hi @JayBraker ,

thanks for asking.

I think you should not compare drawers.mustache and columns2.mustache. You should compare the Boost Union mustache files with the upstream mustache files from Boost Core.

Then, you will see that both in drawers and columns2, Boost Union replaces
```
{{> theme_boost/footer }}
```
with 

```
{{> theme_boost_union/footer }}
{{> theme_boost_union/footnote }}
```

but leaves these items exactly where they were before in the DOM.

This leads to the conclusion that the decision to place the footer elements at a different place in drawers and columns2 were not made by us, they were made by the Moodle core developers.

Having said that, I have to highlight that we modified columns2 just for backwards-compatibility reasons and just quickly tested if a page rendered with columns2 does not break completely. Boost Core still ships with colums2, but does not use it anywhere anymore (see https://github.com/moodle/moodle/blob/master/theme/boost/config.php). It's my understanding that it is just there if any plugin and child-theme still wants to render a page with this layout. 

Did that help?

**Comment by JayBraker** [comment]
Hey @abias

thanks for elaborating on that decision.

Did help alot!

Kind regards
