### ISSUE TITLE
Bug: (Future) config.php sets editor_scss but has no editor.scss, and Boost's editor.scss will never be loaded

### ISSUE THREAD

**Issue by danowar2k** [moodle-an-hochschulen/moodle-theme_boost_union#242]
Mainly a potential minefield for the future, if Boost ever decides to change the contents of its editor.scss file, see https://github.com/moodle/moodle/blob/MOODLE_401_STABLE/theme/boost/scss/editor.scss

boost_union sets editor_scss, see https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/master/config.php#L30

Moodle core works like this:
https://github.com/moodle/moodle/blob/MOODLE_401_STABLE/lib/outputlib.php#L1020

If a theme sets editor_scss, Moodle looks for the files in the theme and loads them. If they aren't present, there's only a a debugging message, see https://github.com/moodle/moodle/blob/MOODLE_401_STABLE/lib/outputlib.php#L1051

Other editor_scss properties from parent themes aren't respected because boost_union sets it. 

This is not a problem because Boost's editor.scss at the moment is pretty empty and redundant, but if Boost ever changes that, boost_union would ignore these scss file changes.

**Comment by danowar2k** [comment]
Here you are: https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/243

**Comment by abias** [comment]
This was solved in #243 243
