### ISSUE TITLE
Improvement: layout/login.php needs child themes to reimplement settings loginformposition and loginformtransparency

### ISSUE THREAD

**Issue by danowar2k** [moodle-an-hochschulen/moodle-theme_boost_union#247]
Boost Union as a whole seems very friendly to child theming in a way so that one can implement a child theme, set Boost Union settings and use those in the child theme without having to reimplement the settings of Boost Union.

One place where this doesn't work is layout/login.php, which requests the page theme's settings object for settings loginformposition and loginformtransparency. A child theme that doesn't reimplement those settings would have to copy and adapt layout/login.php.

See https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/fdd29d81b59c6bc4242d54bade847cb9a1b6efae/layout/login.php#L45-L48

I'll provide a pull request for this.

Aside: Of course, one should perhaps think about child themers who want to reimplement/change Boost Union's settings and perhaps do something like "If the current theme has the setting, use that setting, otherwise fetch Boost Union's setting." That way would probably be more "backwards compatible". But that should best be done in another issue where every spot where theme settings are used are changed to this strategy...

**Comment by abias** [comment]
This was solved in #248
