### ISSUE TITLE
Improvement: Prevent settings duplication in child themes by explicitly using theme_boost_union settings in theme_boost_union_get_pre_scss

### ISSUE THREAD

**Issue by danowar2k** [moodle-an-hochschulen/moodle-theme_boost_union#260]
theme_boost_union_get_pre_scss can be called by either Boost Union itself or child themes of Boost Union.
The parameter $theme is thus not always Boost Union's theme_config, but can also be a child theme's theme_config.

As the method uses $theme->settings->SETTING_NAME , currently child themes have to duplicate Boost Union's settings used in there, because Moodle doesn't let child themes directly inherit parent theme's settings.

By changing all $theme->settings references to get_config('theme_boost_union') calls, Boost Union's settings are always used and child themes do not need to duplicate them.

**Comment by abias** [comment]
This was solved in #261
