### ISSUE TITLE
Improvement: More consistency by using get_config in theme_boost_union_get_main_scss_content

### ISSUE THREAD

**Issue by danowar2k** [moodle-an-hochschulen/moodle-theme_boost_union#262]
The config references of theme_boost_union_get_main_scss_content don't really need to be changed from $theme->settings to get_config() calls, because this function is only referenced by $THEME->scss. And that function is always called with the current theme and only by the theme_config of that theme.

Every child theme will probably (!) have its own main_scss function, so outside of a child theme explicitly calling the Boost Union main_scss function, there would be no need to reimplement the preset setting in child themes.

But still, to be consistent with other places switching to get_config() calls, this should be changed, too.

I'll open a PR.

**Comment by wiebkemueller-hsh** [comment]
Hi @danowar2k can this issue be closed or are there remaining to dos that weren't implemented with the above mentionend merge?

**Comment by abias** [comment]
This issue can now be closed as it is superseded by #267
