### ISSUE TITLE
Suggestion: Avoid duplicating Boost settings 'preset' and 'presetfiles'

### ISSUE THREAD

**Issue by danowar2k** [moodle-an-hochschulen/moodle-theme_boost_union#267]
Boost Union duplicates Boost's 'preset' setting, without adding anything to it. You could avoid duplicating it entirely with appropriate changes to the code. I'll provide a PR.

**Comment by wiebkemueller-hsh** [comment]
Hi @danowar2k can we close this  issue (superseeding #262) as well? I'm just trying to sort/clean up issues...in prep of the going live of the board...

**Comment by abias** [comment]
Solved by #268
