### ISSUE TITLE
Dark navbar hides notification menu buttons

### ISSUE THREAD

**Issue by t-schroeder** [moodle-an-hochschulen/moodle-theme_boost_union#273]
If you use the dark navbar setting the buttons in the notification menu appear white on white background:

![image](https://user-images.githubusercontent.com/24255259/230100979-f75180d8-46ba-4de4-9154-620a385649ab.png)

This is what they should look like:

![image](https://user-images.githubusercontent.com/24255259/230101239-73f18367-1915-4ad2-bb20-66815a32471c.png)

The issue comes from this CSS rule: https://github.com/moodle/moodle/blob/v4.1.2/theme/boost/style/moodle.css#L12377-L12379

So I'm wondering: Should this even be fixed in this theme or rather in Moodle itself?

**Comment by alina-kiz** [comment]
I have the same problem

**Comment by abias** [comment]
This has been solved by #303
