### ISSUE TITLE
Bug: Scrollspy javascript error when using toggle edit not in course page

### ISSUE THREAD

**Issue by steveorulez** [moodle-an-hochschulen/moodle-theme_boost_union#286]
Hello,
when using the edit button not on a course page you will get this javascript error in the console (just for a second)

Uncaught TypeError: Cannot read properties of null (reading 'id')

Same as error #276 you just need to check that the element .section.main exist before adding the eventListener.

amd/build/src/scrollspy.min.js

//Check if .section.main exist
if(!document.querySelector('.section.main')){return;}   

Thanks a lot for the great work!

**Comment by HsH-Wolf** [comment]
Hi @steveorulez : We cannot reproduce this bug. Is it already fixed or could you please provide us a description to reproduce?

**Comment by whuml** [comment]
Hi @steveorulez : meanwhile we managed to reproduce the reported js error (bug) - thanks for reporting this bug and your code suggestions ...
