### ISSUE TITLE
Feature: Show starred courses in navbar

### ISSUE THREAD

**Issue by goggo24** [moodle-an-hochschulen/moodle-theme_boost_union#289]
So that users can switch more quickly to their starred courses (from block course overview) and don't always have to use their dashboard or my courses, we have included them in the navbar. Behind a star icon all favorites are shown. It's again an adminsetting, so that everybody can decide if he/she wants to have it or not.

![grafik](https://user-images.githubusercontent.com/16721900/234927696-7868bcbc-249f-45d0-8bf0-6b1e3b76b721.png)

If it's activated, that's the result:
![grafik](https://user-images.githubusercontent.com/16721900/234927383-a115bf05-7146-436d-986d-058e04ad72d1.png)

If there is interest, we can make a pull request available in the next weeks.

Regards, Eva K. (AMC)

**Comment by lucaboesch** [comment]
Closed by implementing #422.
