### ISSUE TITLE
Feature: Mark External links 

### ISSUE THREAD

**Issue by DHBW-Katja** [moodle-an-hochschulen/moodle-theme_boost_union#307]
Similar to Issue #164: 
It would be nice to mark all links in Moodle that link to other sites (external from our domain) with an icon, i.e. box with arrow up. 

Just as an idea for CSS: 
a[href^="http:"]::after,
a[href^="https:"]::after {
font-family: fontawesome;
content: "\f08e";
font-size: 90%;
padding-left: 3px;
}
a[href*="dhbw.de/"]::after {
content: "" !important;
padding-left:  0 !important
}

**Comment by abias** [comment]
Many thanks for submitting this proposal, @DHBW-Katja !
This was solved in #310 now.
