### ISSUE TITLE
Bug: Hide nodes in primary navigation has no effect on site administration menu item

### ISSUE THREAD

**Issue by stefanscholz** [moodle-an-hochschulen/moodle-theme_boost_union#312]
The setting "Hide nodes in primary navigation" (hidenodesprimarynavigation) is supposed to hide the selected main navigation items. This works fine for "Home", "Dashboard" and "My courses". For "Site administration" it does not have any effect.

![Bildschirmfoto 2023-06-15 um 10 11 31](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/3414705/7036741c-4570-46b2-9782-5c171dc9788e)

Steps to reproduce:

1. Tick the checkbox next to "Site administration" (Boost Union > Feel > Navigation)
2. Save

Expected result: Site administration is no longer visible in the main navigation
Actual result: Site administration remains visible in the main navigation

**Comment by abias** [comment]
This was solved in #314
