### ISSUE TITLE
Bug: Breadcrumb navigation is partial in wrong order

### ISSUE THREAD

**Issue by stdoma** [moodle-an-hochschulen/moodle-theme_boost_union#317]
Hello!
Breadcrumb navigation in the course is good & important! - Thanks for the option to display.

Breadcrumb navigation is not displayed correctly in all cases.
I use the MultiTopic format for courses (https://moodle.org/plugins/format_multitopic).
There, the navigation on the main page looks like this: the order of the course areas and course sections is reversed and the course itself is missing.
![Screenshot 2023-06-19 083900](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/92015860/d6c4d51e-000c-4c0a-b7f4-1bdde7371c3f)

On the individual sub-sites of the activities, the order is correct:
![Screenshot 2023-06-19 084143](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/92015860/36098d1d-7c61-48c3-9555-bfeb4dcf8900)

It's not the course format. Breadcrumb navigation is not included there.
I haven't been able to figure out the actual code yet...

**Comment by stdoma** [comment]
Yesterday I took a quick look at the thing in the code.
I haven't analyzed it in detail yet.
Since the problem occurs regardless of the course format and it bothered me that the course itself also disappeared from the breabcrumbs, I modified the code a bit.
However, the solution is a bit ugly.

classes/boostnavbar.php
After the navigation is assembled I rotate the items of the object classes ("navigation_node", "breadcrumb_navigation_node").
In itself, the order of the elements is correct.
The deletion of the course can also be undone quite quickly.
After that I have the correct representation. Even if it is technically not entirely clean.
![Screenshot 2023-06-23 153243](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/92015860/a86f9ff7-b385-4399-b373-056173167a83)

If necessary, I can upload the file changes.

**Comment by danowar2k** [comment]
Currently this is influenced by two settings: core/navshowcategories and boost_union/categorybreadcrumbs.

This behaviour can be experienced (pseudo code):

```
if (navshowcategories && boost_union/categorybreadcrumbs) {
   The navbar contains duplicate categories, one of which is removed because its text is the same as the others (Moodle core function)
   Left of a course's section are course categories, and right of the section are categories (basically C1 > C2 > Section > C1 > C2)
}
if (navshowcategories && !boost_union/categorybreadcrumbs) {
   The navbar doesn't contain any course categories (because no course node is shown there is only one item in the navbar, so it isn't shown at all) (reason: Union removes all categories from the breadcrumb)
}
if (!navshowcategories && boost_union/categorybreadcrumbs) {
   The navbar contains the section followed by the categories from top to bottom (reason: Union appends the categories after the section)
}
```

I'd suggest the following instead:

```
if (navshowcategories || boost_union/categorybreadcrumbs) {
   Result: C1 > C2 > C3 > Kurs oder Sektion
}
```

I'll do a PR....

**Comment by danowar2k** [comment]
Sorry, couldn't read it...
```
//HOST - SD: Start Änderungen
//drehen der Items in der Breadcrumb-Navigation
//Reihenfolge ist per default vertauscht (Kursbereiche stehen hinten)
if (!empty($this->items)) {
   $host_arrNavbarNew[] = null;
   $host_arrNodeNames = array("navigation_node", "breadcrumb_navigation_node");
   foreach ($host_arrNodeNames as $host_nodeName) { 
      foreach ($this->items as $host_navBarItem) {
         if (get_class($host_navBarItem) == $host_nodeName) {
             $host_arrNavbarNew[] = $host_navBarItem;
         }
      } 
   } 
   $this->items = $host_arrNavbarNew; 
} 
//HOST - SD: Ende Änderungen
```

**Comment by lucaboesch** [comment]
Please try to add a test in tests/behat/theme_boost_union_feelsettings_navigation.feature for this then as well @danowar2k.
Thanks in advance!

**Comment by stdoma** [comment]
Hi @danowar2k, attached is the file with my changes.
[boostnavbar.zip](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/files/13447516/boostnavbar.zip)

In the navigation hierarchy array, the individual elements of a node object are in the correct order. The order of the node objects is not correct. Therefore, I just use a different order and get all the elements of the object type one after the other.
I just looked at the array used to build the navigation. The navshowcategories setting has no effect on this.

**Comment by danowar2k** [comment]
I analysed the core settings and the categorybreadcrumbs setting and now know their behaviour.

This now leads to me wondering whether it would be better to fix the wrong order of section > category or to first discuss why the  setting categorybreadcrumbs exists while enabling navshowcategories and navshowmycoursecategories also has the desired effect of adding categories to the course breadcrumb (meaning I don't get what's missing there that Union fixes with its setting).

One could always instead add links to those categories missing them and prevent Moodle from not showing the breadcrumb when only one category is present.

**Comment by danowar2k** [comment]
Okay, the code for fixing the section links placement is done at least...

```
            if (get_config('theme_boost_union', 'categorybreadcrumbs') == THEME_BOOST_UNION_SETTING_SELECT_YES) {
                $itemsWithCategories = [];
                foreach ($this->items as $item) {
                    if ($item->type == \breadcrumb_navigation_node::TYPE_COURSE) {
                        // Add the categories breadcrumb navigation nodes.
                        foreach (array_reverse($this->get_categories()) as $category) {
                            $context = \context_coursecat::instance($category->id);
                            if (!\core_course_category::can_view_category($category)) {
                                continue;
                            }

                            $displaycontext = \context_helper::get_navigation_filter_context($context);
                            $url = new moodle_url('/course/index.php', ['categoryid' => $category->id]);
                            $name = format_string($category->name, true, ['context' => $displaycontext]);
                            $categorynode = \breadcrumb_navigation_node::create($name, $url, \breadcrumb_navigation_node::TYPE_CATEGORY,
                                null, $category->id);
                            if (!$category->visible) {
                                $categorynode->hidden = true;
                            }
                            $itemsWithCategories[] = $categorynode;
                        }
                    }
                    $itemsWithCategories[] = $item;
                }
                $this->items = $itemsWithCategories;
            }

```

**Comment by danowar2k** [comment]
> Please try to add a test in tests/behat/theme_boost_union_feelsettings_navigation.feature for this then as well @danowar2k. Thanks in advance!

Whoops, overlooked that...

**Comment by danowar2k** [comment]
There it is finally: https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/483
