### ISSUE TITLE
Bug: Overwriting module purposes does not affect all places where the activity icon is displayed

### ISSUE THREAD

**Issue by larsbonczek** [moodle-an-hochschulen/moodle-theme_boost_union#318]
This refers to the feature requested in #288. There are at least two places in which module icons are displayed that are not affected by the code in #308 when the module purpose is changed:

1. The activity page itself
2. The "Recently accessed items" block (block_recentlyaccesseditems)

### Example
Moodle Version 4.1.3+ (Build: 20230427)

The purpose of the quiz module has been changed to "content" (blue).

Quiz icon on the course page (correct):
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/44197504/93edab80-d395-4a77-8465-5efcb06a4484)

Quiz icon on the quiz page (wrong):
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/44197504/bfefae8e-db0c-4271-a955-ff8a0706261f)

Quiz icon in the "Recently accessed items" block (wrong):
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/44197504/aeadd40e-075a-4e49-bb2a-a6de0c626281)

I think this feature (changing module purpose) should not be implemented in this way (via CSS), since this solution does not actually change the module's purpose, it just pretends to do so by changing the color in some places. This might lead to unexpected behavior if Moodle core ever uses the module purpose for something other than the icon color. Maybe if we call it "changing the module color" instead, this feature it would be less misleading. This could be done together with #294.

**Comment by abias** [comment]
Hi @larsbonczek ,

thank you for raising this issue.
I agree that there are more places in Moodle where the icon colors have to be changed. This was also mentioned in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/288#issuecomment-1609004068 and there was a patch provided by @goggo24 as well.

I have submitted a PR on #335 with the changes by @goggo24 plus a fix for block_timeline which was affected by the same issue. If you have time to submit a peer review there, that would be great.

On another note, I agree that this feature should not be built with CSS. However, it's the only way to built it as far as I see as the theme can't hook into the `FEATURE_MOD_PURPOSE` process how Moodle core asks activity plugins about their purpose. If you know away, don't hesitate to tell us.

Cheers,
Alex

**Comment by abias** [comment]
I have merged the PR #335 now, but don't hesitate to add your feedback if you spot anything which does not make sense to you.

Cheers,
Alex
