### ISSUE TITLE
Bug: Changing module purpose to "other" makes icon invisible

### ISSUE THREAD

**Issue by larsbonczek** [moodle-an-hochschulen/moodle-theme_boost_union#319]
This refers to the feature requested in #288 (implemented in #308). When a module purpose is changed to other, the icon becomes invisible. This is because the white monologo is not visible on the white background. 

### Example
Moodle Version 4.1.3+ (Build: 20230427) 

Quiz activity with original purpose:
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/44197504/99d631df-f26c-4dcf-b65d-ff4a929b516e)

Quiz activity with purpose "other":
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/44197504/55408341-f31c-451b-861d-cff2f729db1f)

**Comment by abias** [comment]
This was solved in #320
