### ISSUE TITLE
Feature: Built-in imprint page

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#32]
Basically every Moodle site should have an imprint. With a third-party plugin like local_staticpage, this can be implemented quite easily.

Nevertheless, this approach has the downside that you need yet another plugin (and, particularly looking at local_staticpage, that the user who creates the imprint has to understand HTML).

It would be worthwhile to add a feature which:
* Allows admins to write in imprint within the theme settings in a rich-text editor
* Show this imprint on a page like /theme/boost_union/pages/imprint.php
* Automatically add a link to the imprint to the page footer

**Comment by abias** [comment]
I submitted a PR for this issue in #43

**Comment by lucaboesch** [comment]
Done.
Thanks, @abias !
