### ISSUE TITLE
Improvement: Shrink description_format column size in theme_boost_union_flavours table

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#321]
The description_format column in the theme_boost_union_flavours table has a size of 10 (see https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/master/db/install.xml#L12), but in fact it only needs to have size of 2 given the data which is stored there.

It would be worthwhile to shrink this column in db/install.xml and db/upgrade.php

**Comment by Harshal662** [comment]
I can do that

**Comment by abias** [comment]
@Harshal662 - that would be awesome!
Please don't hesitate to create a PR for this issue.

**Comment by lucaboesch** [comment]
Fixed by #505.
