### ISSUE TITLE
Bug: "theme_boost_union | markexternallinks" double labeling in the footer

### ISSUE THREAD

**Issue by stdoma** [moodle-an-hochschulen/moodle-theme_boost_union#323]
Hello!
I have activated the setting to mark external links.
The help link is already marked in the footer by the system.
As a result, the link is marked twice.

(I've customized the footer, so it looks a little different than the default.)
![Screenshot 2023-06-21 153826](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/92015860/9070be71-1292-45c2-9ee0-9411ef104b6e)

**Comment by ralf-krause** [comment]
Yes, the external links are double labeled. In my case I get no icon for the label from Boost union.

<img width="362" alt="moodle-copyright" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/27956839/3eeddb9a-8227-4849-a7d0-7fad3fe51148">

<img width="777" alt="moodle-server-environment" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/27956839/7a116dc5-3321-4389-8654-760adf350767">

**Comment by ksteitz** [comment]
This behaviour is a bug affecting 4.2 only, see also https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/310#issuecomment-1602791784
It is caused by the change to font awesome 6. 
There will be a fix soon...

**Comment by ralf-krause** [comment]
Okay, we get the empty icons only with Moodle 4.2. 
But you marked this complete doublelabeling issue for 4.2 only. This is incorrect. My screenshot shows Moodle 4.0.8. The external links are doublelabeled.

<img width="601" alt="moodle-server-environment-408" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/27956839/e6653306-ef6f-447c-887b-ca86935b734f">

**Comment by ksteitz** [comment]
The "Bug: Font Awesome external link icon broken in Moodle 4.2+" is now in a separate issue: 
https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/327

**Comment by abias** [comment]
Thank you all for raising and discussing this issue.

I have just pushed 48b3145497fb3ed9f91b738fadb01b99c31d99d5 for Moodle 4.2 and 5d14ac5d66209240bb1633c402c83cefce670182 for Moodle 4.1 which should hopefully fix this issue.

Cheers,
Alex
