### ISSUE TITLE
Bug: $blockregionoutsiderightwidth and $blockregionoutsideleftwidth are missing default values in scss

### ISSUE THREAD

**Issue by danowar2k** [moodle-an-hochschulen/moodle-theme_boost_union#325]
If somehow the values for blockregionoutsiderightwidth or blockregionoutsideleftwidth are not set from within the GUI or the values are set as empty, the theme can't be built because the variables don't have default values. (see https://sass-lang.com/documentation/variables#default-values)

These default values should probably be set at the beginning of post.scss or in pre.scss, depending on where the scss generated by setting the variables is placed.

**Comment by danowar2k** [comment]
Same as #326.

**Comment by abias** [comment]
Thank you for raising this issue!
I cannot imagine a case how the prerequisites for this bug could be triggered, but there was a gap in the code which sets the SCSS variables which I fixed in PR #329.

**Comment by abias** [comment]
This was fixed in #329
