### ISSUE TITLE
Bug: Fehler beim Erzeugen der scss-Datein bei fehlendem Wert für blockregionoutsideleftwidth oder blockregionoutsiderightwidth

### ISSUE THREAD

**Issue by HoffmannP** [moodle-an-hochschulen/moodle-theme_boost_union#326]
Aus nicht mehr nachvollziehbaren Gründen waren in unserer Datenbank die Werte `blockregionoutsideleftwidth` und `blockregionoutsiderightwidth` nicht gesetzt. Daraufhin wurden die entsprechenden Variablen in scss nicht gesetzt und beim Kompilieren der scss-Datei kam es zu einem Fehler der leider still und leise im Äther verschwand. Ich schlage vor, wenn die Variablen nicht gesetzt sind (bzw leer), dann sollte der Default-Wert ausgegeben werden und nicht etwa die Variable im SCSS ausgelassen.

Betrifft
https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/5326b632226b2c466319200b1762ce70a1d2237d/lib.php#L204-L206
und
https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/5326b632226b2c466319200b1762ce70a1d2237d/lib.php#L207-L209

Grundsätzlich kann das Problem, dass SCSS-Variablen fehlen, aber auch an anderen Stellen in der gleichen Funktion auftauchen. Hier wäre eine Fehlermeldung sinnvoll, da selbst die Debugging-Ausgabe von SCSS nicht gut darauf hinweist, wo der Fehler aufgetaucht ist:

```
Undefined variable $blockregionoutsideleftwidth: line: 603, column: 13
Call Stack:
#0 mixin media-breakpoint-up (unknown file) on line 660
```

**Comment by danowar2k** [comment]
Seltsam, dass das Problem von zwei gleichzeitig bemerkt wird...Im Code sehe ich aber in der Richtung nichts auffälliges...

**Comment by BerengarWLehr** [comment]
Wie meinst du "nichts auffälliges"?

**Comment by danowar2k** [comment]
Welche Version von Union war vorher drauf?

Unseren Aufzeichnungen zufolge bei uns 4.0-r8, danach 4.1-r7 jetzt. In Test, wo es keine Probleme gab, wurde wohl von v4.1-r2 auf v4.1-r7 aktualisiert. Seufz...

**Comment by abias** [comment]
Thank you for raising this issue!

I cannot imagine a case how the prerequisites for this bug could be triggered, but there was a gap in the code which sets the SCSS variables which I fixed in PR #329.

**Comment by abias** [comment]
This was fixed in #329
