### ISSUE TITLE
Bug: Font Awesome external link icon broken in Moodle 4.2+

### ISSUE THREAD

**Issue by ShUl0w** [moodle-an-hochschulen/moodle-theme_boost_union#327]
Due to a major upgrade of Font Awesome from 4.x to 6.x in Moodle 4.2, some Font Awesome icons are not properly displayed:
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/37832993/80831569-1191-4954-bae8-cac163e05868)

I have already begun work on a bugfix, which should be ready shortly. However, there is one obstacle to discuss: from Font Awesome 6 onward, the "normal" font-style as well as the corresponding font-weight "400" appear to be a pro feature, meaning they are absent from Moodle, at least from what I can tell. Font Awesome 6 only seems to offer the font-weight "900" style.

Thus, a fallback for Moodle <= 4.1 needs to be implemented when moving up to Font Awesome 6. This brings with it some questions regarding the cleanliness of the codebase when moving forward.

I therefore propose a "quickfix" to solve the missing icon issue asap, and then figure out how to move forward. For the time being, we need to decide if a bold icon for Moodle <= 4.1 is okay, or if we should implement version checks to retain the "original" look (see screenshot below for comparison; left 4.2, right 4.1).

![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/37832993/6c4b5473-5c03-49d7-a3e7-2c0c50b4a15c)

**Comment by ShUl0w** [comment]
I've opened a draft PR, see #328

**Comment by ShUl0w** [comment]
As an idea, we could also implement a kind of boost-union font-face, which should - unless my CSS-knowledge eludes me - provide even cleaner fallback capabilities:

`
@font-face {
  font-family: "Boost Union Font Awesome";
  src: local("Font Awesome 6 Free"), local("FontAwesome");
  font-weight: 900;
}
`
Since I'm not as experienced in Moodle development yet, is it maybe possible to pass a variable to the SCSS compiler with which we could set the font-weight dynamically, depending on the Moodle version?

**Comment by abias** [comment]
Thank you all for raising and discussing this issue.

I have just pushed 48b3145497fb3ed9f91b738fadb01b99c31d99d5 for Moodle 4.2 and 5d14ac5d66209240bb1633c402c83cefce670182 for Moodle 4.1 which should hopefully fix this issue.

Cheers,
Alex
