### ISSUE TITLE
Bug: In master, foreach() argument must be of type array|object warning appears. 

### ISSUE THREAD

**Issue by lucaboesch** [moodle-an-hochschulen/moodle-theme_boost_union#330]
This appears in (PHP8.1) master (hence Moodle 4.3pre):

`Warning: foreach() argument must be of type array|object, bool given in …/theme/boost_union/locallib.php on line 1203`

when a site is rebased to a weekly release and admin/index.php is called and the site wants to update.

<img width="1512" alt="boost_union_warning" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/377279/458e1423-f0ac-4634-843a-ed451da949bf">

**Comment by lucaboesch** [comment]
I think I was on a old branch. Didn't happen when updating Moodle 4.2.

**Comment by lucaboesch** [comment]
No, it is legit. But it appears only if no CSS cached folder is present.

**Comment by abias** [comment]
This was fixed in #331
