### ISSUE TITLE
Improvement: Change order of authentication methods on the login page

### ISSUE THREAD

**Issue by AntonT76** [moodle-an-hochschulen/moodle-theme_boost_union#332]
Hi,

we are using more than one authentication methods (OpenID Connect, Manual Accounts and Guest Accounts). It would be nice if there is a way to change the order of the login via backend, eg:
- 1. OpenID
- 2. manual accounts
- 3. guest accounts

Normally the authentication methods are listet like this:
- 1. manual accounts
- 2. OpenID
- 3. guest accounts

In addition, it should be possible to insdert a text under every authentication method to display information (eg: "Please use this login if you have ..." )

thanks, br Anton

**Comment by wiebkemueller-hsh** [comment]
Hi Anton, 

you mention "backend", but maybe this frontend solution is still attractive for you?
https://moodle.hu-berlin.de/mod/forum/discuss.php?d=942319

Pls. don't hesitate to get in touch if you're not subscribed to the linked forum I can forward the (S)CSS-template to you.

Regards
Wiebke

**Comment by wiebkemueller-hsh** [comment]
Hi @AntonT76 I'll close this, since the issue #504 will take care of it. for some reasons, we've skipped this issue, but it will be done! Regards Wiebke
