### ISSUE TITLE
Test: Add tests for smart menu visibility restriction by date

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#364]
This is a follow-up issue to #300.

In https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/f5d593275c6ec4e8d2e446e3f82a51823e2f6e87/tests/behat/theme_boost_union_menu_rules.feature and https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/f5d593275c6ec4e8d2e446e3f82a51823e2f6e87/tests/behat/theme_boost_union_menuitem_rules.feature, there are test scenarios for restricting the visibility of smart menus and smart menu items per cohort, per role and per language. But there aren't any tests for restricting the visibility of smart menus and smart menu items per date which is a usable feature as well.

**Comment by lucaboesch** [comment]
This can be closed.
