### ISSUE TITLE
Smart menu entries does not appear

### ISSUE THREAD

**Issue by kaaermes** [moodle-an-hochschulen/moodle-theme_boost_union#368]
I created a smart menu within the main navigation and also added two items > but they doesn't appear. Instead I can only see a small blank box as you can see in the sceeenshot.

I don't know if I mussed any settings … 

<img width="1706" alt="Bildschirmfoto 2023-08-23 um 14 30 22" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/128585815/47d9bcaa-a103-47fd-a242-1cbff32fa03c">

**Comment by stefanscholz** [comment]
Hi @kaaermes ,

You might want to check if you have used any of the responsive settings, which hide menu items on the selected viewports. 

Another possibility would be that you chose "hide title". 

For the dynamic courses menu item, you might have configured something that does not have results, e.g. that a specific category you selected simply does not have any courses where you are enrolled.

Hope this helps! If it does not, please provide more details in the configuration and we can review.

Best
Stefan

**Comment by kaaermes** [comment]
Hi @stefanscholz 

yes you are right – I checked those settings. 

But after unchecking – the menu looks like this now

<img width="910" alt="Bildschirmfoto 2023-08-28 um 10 22 24" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/128585815/bec6591a-9063-4f36-a316-815da94fc5c1">


I can only see the menu items in the white box when hovering over them … 

:-)
Kathleen

**Comment by kaaermes** [comment]
Hi @wiebkemueller-hsh my issue is older than Berengars – but if you like, you can close it. main thing is that it will be fixed :-)

**Comment by wiebkemueller-hsh** [comment]
Hi @kaaermes I'll close this one because the other one contains first ideas on how to fix/workaround...I'll classify the other one as a bug so it will be looked after.
