### ISSUE TITLE
Code Refactoring: function theme_boost_union_rrmdir() could be replaced with moodlelib.php function remove_dir()

### ISSUE THREAD

**Issue by danowar2k** [moodle-an-hochschulen/moodle-theme_boost_union#369]
The core function remove_dir() (see https://github.com/moodle/moodle/blob/cccc00954d246448556a3e97874fc2288bdf9674/lib/moodlelib.php#L9999-L10038) does the same as the function theme_boost_union_rrmdir() from locallib.php

To lower difficulty managing the code this could be refactored to use the core function.

**Comment by abias** [comment]
This was solved in #372
