### ISSUE TITLE
Bug: setting activitypurpose_modname is accessed via $theme->settings

### ISSUE THREAD

**Issue by danowar2k** [moodle-an-hochschulen/moodle-theme_boost_union#370]
For now theme_boost_union uses standardizes theme settings access to get_config() calls so that child themes do not need to reimplement Union's settings.

theme_boost_union_get_extra_scss uses $theme->settings when getting activitypurpose_MODNAME settings. This should be standardized.

**Comment by abias** [comment]
This was solved in #371
