### ISSUE TITLE
Test: Complete the test set for the smart menus feature

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#375]
This is a follow-up issue to #300 

The test set for the smart menus feature is incomplete, unfortunately.

The following tests for smart menu options should be added:

* Advanced settings -> More menu behavior 
* Card appearance ->  Overflow behavior

The following tests for smart menu items should be added:

* General -> Type -> Heading (There is no dedicated tests for testing that headings work)
* General -> Type -> Static (There is no dedicated tests for testing that static menu items work
* Appearance -> Mode -> Submenu (There is no test which tests the third menu level)
* Appearance -> Icon
* Appearance -> Display options
* Appearance -> Tooltip
* Appearance -> Order
* Appearance -> Responsive
* Card appearance -> Image
* Card appearance -> Text position
* Card appearance -> Text color
* Card appearance -> Background color

If a particular feature cannot be tested with Behat, it should be mentioned anyway in a Behat scenario with a note like 
https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/master/tests/behat/theme_boost_union_looksettings_sitebranding.feature#L141-L142 for the sake of completeness

**Comment by lucaboesch** [comment]
Fixed by #501.
Closing.
