### ISSUE TITLE
Bug: Smart menus do not support multilanguage filters yet

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#376]
This is a follow-up issue to #300 and related to #358

Currently, smart menus do not support multilange filters yet.

Multilanguage strings should be supported for:
* Menu titles
* Menu descriptions
* Menu item tooltips
* Menu items which are auto-generated from dynamic courses

It should be supported in all areas where this data is presented, i.e. in all 4 smart menu areas (Main, User, Bottombar, Menubar) and on the smart menu management pages as well.

As the smart menus are cached, the cache has to be cleared as soon as the user changes the language in his profile settings or with the language switcher in the user menu.

**Comment by wiebkemueller-hsh** [comment]
might be fixed with #358 , to be checked by testing team (therefore added label documentation)

**Comment by abias** [comment]
@wiebkemueller-hsh - I can say that this issue is not fixed with #358 yet, but a patch for #358 is already in the works as well.
