### ISSUE TITLE
Feature: Dark navbar

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#39]
Boost Campus provided the possibility to invert the navbar and make it dark.

It would be worthwhile to port this feature over to Boost Union.

**Comment by abias** [comment]
@t-schroeder - As discussed in the HU Forums, I have added you as assignee to this issue.

**Comment by Amrita1991** [comment]
Hi,

I have created a pull request for this feature
https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/63

**Comment by lucaboesch** [comment]
I heard the request of having not just dark but a configurable color.

**Comment by andremenrath** [comment]
@Amrita1991 @lucaboesch @t-schroeder 
Is anyone already putting work into this (Not only dark, but branding-color styled navbar)? We at AMC would like to see this future and could work on this. Should we use a different issue for it?

**Comment by lucaboesch** [comment]
I from my point can say: go ahead, @andremenrath !
What about you, @Amrita1991 and @t-schroeder ?

**Comment by t-schroeder** [comment]
@lucaboesch What should be the default color if the color is made configurable?

@andremenrath We were not yet planning to work on this. So if you want to implement this, that's fine with me. Making the color configurable would obsolete the dark navbar setting. The proper way would probably be to close this issue and create a new one.

**Comment by abias** [comment]
As @Amrita1991 was the first one to submit a PR to this issue, I have changed the assignee of this issue.
@Amrita1991 's PR was finally reviewed any is now superceeded by #224 which will hopefully be merged soon and which will then solve this issue.

**Comment by abias** [comment]
As #224 was merged just now, this issue is solved now.
