### ISSUE TITLE
Bug: Installation problem v4.1-r12 ("Required Moodle version [2022112805.04]")

### ISSUE THREAD

**Issue by readyandnot** [moodle-an-hochschulen/moodle-theme_boost_union#401]
Hi there,

I tried to install version 4.1-r12 today after the #390 problems but am now getting a weird error message:
"[Error] Required Moodle version [2022112805.04]"

The server however is running on freshly set up, mint-condition 4.1.5. Does anybody know what this is about?

Thanks,
Simon

**Comment by christianwolters** [comment]
Hi @readyandnot,

maybe this ".04" is a typo.

Before a fix in the repo is in and you want to try to fix it your self:

change line 30 in version.php of boost_union directory to:

`$plugin->requires = 2022112805;`

Cheers,
Christian

**Comment by readyandnot** [comment]
Thanks Christian, that worked like a charm. For anybody else having the same issue, this seems to be all you need to fix.

**Comment by abias** [comment]
This ".04" isn't a typo.
You need a weekly release of Moodle core which came after the 4.1.5 minor release to upgrade to the latest version of Boost Union.

If you do not have this Moodle core version installed, it's correct that you can't upgrade theme_boost_union.
And if you do have it installed, you should not see this error message.

May I ask you what your exact Moodle core version number is? You find it in /version.php of your Moodle installation directory.

PS: We have used this dot-notation before in Boost Campus (see https://github.com/moodle-an-hochschulen/moodle-theme_boost_campus/blob/75ba8795cd124693e72ce64ff09f164f751735b5/version.php#L30) and it worked fine back then.

Cheers,
Alex

**Comment by christianwolters** [comment]
Ah shoot, I was almost certain, that something like that was the case (so wild guessing...and maybe)

Sorry, @abias : /

**Comment by readyandnot** [comment]
It was 2022112805.00 before, so I installed a new version now and that worked just as expected.

Thanks everyone for your help!

**Comment by abias** [comment]
Hi @readyandnot ,

thank you for your confirmation.
In this case, the code did what it was supposed to do :)

Cheers,
Alex
