### ISSUE TITLE
Improvement: Configurable sort order in menu items of smart menu

### ISSUE THREAD

**Issue by wiebkemueller-hsh** [moodle-an-hochschulen/moodle-theme_boost_union#403]
This is a follow-up to #300 

As an admin I would like to decide on the way dynamically created menu items in a smart menu are sorted. The current standard behaviour is having the sort order sorted "Alphabetically by Shortname ascendnig", it would be better to have the possibility to choose whether to sort the menu items:

- Alphabetically by Fullname ascending
- Alphabetically by Fullname descending
- Alphabetically by Shortname ascending
- Alphabetically by Shortname descending
- Numerically by Course-ID ascending
- Numerically by Course-ID descending
- Alphabetically by Course-ID NUMBER ascending
- Alphabetically by Course-ID NUMBER descending

**Comment by lucaboesch** [comment]
Needless (but maybe not) that in case of multilangual menu items the order (the starting letters) can be different. So, it's more of a 'Alphabetically by Fullname in the chosen language ascending'.

**Comment by abias** [comment]
This was solved by #503
