### ISSUE TITLE
Make sure smart menu "locations" is filled with value

### ISSUE THREAD

**Issue by wiebkemueller-hsh** [moodle-an-hochschulen/moodle-theme_boost_union#404]
This is a follow-up issue to #300 

As a user (admin) I would like to be notifyed by the system/form if a mandatory item is missing in order to show the smart menu I created.
Since it is necessary to specify a location in order to show the smart menu in the frontend, the configuration of smart menu locations field should be a mandatory field or be filled with a default start value on creation of a new smart menu.

Notes:

- Users might be confused when all mandatory fields have been filled and the menu is still not shown. 
- In case a smart menu is used as a mere field for storing data for other (future) purposes, there should be an extra item in the options list, specifying the purpose (e.g. "no location, only data storage").
- The hiding of a smart menu in preparation can be done via actions (hide).

**Comment by wiebkemueller-hsh** [comment]
This is ready for dev and time has to be found to realize it. Could be a good first issue for new developers!

**Comment by kaaermes** [comment]
field "Menu location(s)" is mandatory 

Moodle 4.1.10 > OK
Moodle 4.2.7 > OK

<img width="786" alt="Bildschirmfoto 2024-05-13 um 15 29 37" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/128585815/d6451fbc-e91e-4793-abbc-ecb003b9cb96">
