### ISSUE TITLE
Behat tests: Forced outside of more menu

### ISSUE THREAD

**Issue by wiebkemueller-hsh** [moodle-an-hochschulen/moodle-theme_boost_union#408]
This is a follow-up issue to #300 

Add missing behat test for functionality "forced inside/outside of more menu"

**Comment by wiebkemueller-hsh** [comment]
Steps to reproduce the bug:

1. create different smart menus, location main menu
2. configure the smart menu sitting at the very right position as "keep outside of more menu"
3. change browser size and view the menu item is not kept outside of the more menu but will be in the more menu at first

**Comment by abias** [comment]
This test was already added in #375 / #501.
