### ISSUE TITLE
Cannot install update for Moodle 4.2

### ISSUE THREAD

**Issue by kpatzwald** [moodle-an-hochschulen/moodle-theme_boost_union#410]
Hi,

I am using Moodle 4.2 I get the notfication that there is an update for Boost_Union.

When I try to update I get the following message:
Installing available updates
Downloading theme_boost_union ... OK
Validating theme_boost_union ... Error
  [Error] Required Moodle version [2023042402.04] 
Installation aborted due to validation failure

I also tried to install manual ... without look.

Best regards
Kay

**Comment by abias** [comment]
Hi @kpatzwald ,

Please have a look at the changelog:
https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/master/CHANGES.md#v42-r2

There, we have noted:
> If you intend to use this release of Boost Union, please update Moodle core to the latest Moodle core 4.2.2+ or wait some more days for 4.2.3. 

Thanks,
Alex
