### ISSUE TITLE
Single activity format contains unnecessary second level of navigation items

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#415]
Steps to reproduce:
* Create a course
* Change the course's course format to "Single activity format"
* Go to the course main page
* Open the course level navigation menu (which has become a dropdown menu in the single activity format)

Expected result:
* The dropdown contains only one level of navigation items like like theme_boost
![grafik](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/1092118/7bedc12f-940f-4a42-ad4d-754e74b3b8d1)

Actual result:
* The dropdown contains two levels of navigation items
* Additionally, the second level is oddly indented
![grafik](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/1092118/d25c496d-2516-4152-a61c-445db7351c3f)

Analysis:
* This seems to be a regression of the navigation menu template changes which have been made within the smart menus feature.

**Comment by abias** [comment]
I will take care that this issue gets fixed.

**Comment by mwilday** [comment]
I can confirm this is an issue for us as well. Is there an ETA for this fix? Not a rush, just curious.

**Comment by wiebkemueller-hsh** [comment]
Hello @mwilday and others, thank you for asking. In the meatime we have been able to address this issue with the development. It won't be forgotten, and we'll integrate it in the next dev cycle. In case we miss out to post it here again - you will be notified via the status of the issue when it's handed over to review. Regards! Wiebke

**Comment by kaaermes** [comment]
patch tested – bug fixed. everything looks properly now
