### ISSUE TITLE
The “Back to top” button doesn't show up

### ISSUE THREAD

**Issue by DmitrySharabin** [moodle-an-hochschulen/moodle-theme_boost_union#419]
Hey there, fantastic team, 👋🏻

A few days ago, the “Back to top” button stopped appearing on long pages. I'm unsure when it began, but I might suggest that after updating to Moodle 4.3 (I might be mistaken, though).

<img width="312" alt="SCR-20231011-kmho" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/9166277/129043f8-3ca4-4920-8a51-b828389638db">

At first, I thought it was because I was on an outdated version of the theme. However, the issue remains after I switched to the latest release.

<img width="1241" alt="SCR-20231011-kipv" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/9166277/840c5e73-0f81-4a23-bb98-4369d1a1aefc">

I checked all the settings—the back-to-top button feature is on.

<img width="1115" alt="SCR-20231011-kgvk" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/9166277/c7dc701a-ed51-4fc6-977b-176627222a16">

But the button doesn't appear.

<img width="1115" alt="SCR-20231011-khfg" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/9166277/653aa6b8-4ff4-441a-bc96-9e5daaacbefb">

Even though it's in the DOM, it's hidden.

<img width="1381" alt="SCR-20231011-khtl" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/9166277/3856eb65-4bd9-47a3-b6ca-8fcaef562533">

As far as I can judge, the click event handler is also registered.

<img width="725" alt="SCR-20231011-kiix" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/9166277/28cf5e7c-637d-476e-8a06-3a078e101b63">

Is there a chance I did something wrong, and is there a way to re-enable it somehow (I tried to turn off the feature and enable it again—without luck)?

Thank you!

Regards,
Dmitry

**Comment by abias** [comment]
Thank you, @DmitrySharabin, for reporting this issue.
I am currently preparing the 4.3 upgrade of Boost Union and have just fixed this issue in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/commit/da9217afa95b3473ff2b66285e35723e03e6f377. It will be part of the 4.3 which will be published soon.

**Comment by DmitrySharabin** [comment]
What a fantastic news! Thank you, @abias, for having fixed it. 🥳
