### ISSUE TITLE
Moodle version fail?

### ISSUE THREAD

**Issue by Richardvi** [moodle-an-hochschulen/moodle-theme_boost_union#433]
I'm currently on Moodle 4.2.1 (Build: 20230612) and Moodle reports, in the plugin overview, an update for Boost Union.

Currently I have Boost Union v4.1-r7 2023010511 running and it is reporting there's a new version available: There is a new version 2023090102 available! Release v4.2-r3

However, when I try to install this new Boost Union version it fails with this error:

![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/5486910/e85056bf-aa14-425d-9b7e-c5576069a2c3)

Why is this? My Moodle version is above the version required?

**Comment by ak4t0sh** [comment]
FYI facing same issue on moodle 4.1.2 while trying to install v4.1-r13 (2023010524)
Upgrading to latest moodle version 4.1 (4.1.6+ (Build: 20231020)) fixed the issue.

**Comment by abias** [comment]
Hi all,

This glitch has been reported by others before and I have answered and explained it on https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/410#issuecomment-1741696008.

Cheers,
Alex

**Comment by Richardvi** [comment]
@abias 
I don't know exactly how it works, but usually Moodle doesn't report that there's a new update available for a plugin if you are not on the required version. It would also be very confusing when you (f.e.) are running Moodle 3.X and it reports many plugin updates available that only work for Moodle 4.X

So I don't think it's a glitch, I think something is wrong in the pre-check reporting that there's an update available?
