### ISSUE TITLE
Show logged in user, first name and last name

### ISSUE THREAD

**Issue by akolar123** [moodle-an-hochschulen/moodle-theme_boost_union#439]
Hello,

I'm sure that there is a documentation writen for this issue but I can't seem to find the right answer. 

I have installed the Boost Union theme on my Moodle site, but I can't seem to find the option where the Top Navbar would show current users First and Last name credentials, only the profile picture is visible, but i would like to show users First and Last name with it.

This is what it shows now:
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/146717341/3705689f-9bd5-4991-9708-3eb936e3a399)

What I want it to show: (sorry for the blury picture but I think you know what I mean)
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/146717341/ab04b280-24c2-4c42-8a42-338a66e0fce2)

**Comment by wiebkemueller-hsh** [comment]
Hello @akolar123 

I found out two things:

1. Classic theme provides the name + profile pic, see here
https://qa.moodledemo.net/my/courses.php?theme=classic

![Image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/72548805/6fcc4030-19c5-4eb0-a145-7cac94f11589)

2. please see here for more information in the forum: 
https://moodle.org/mod/forum/discuss.php?d=438328

It has to be discussed whether Boost Union will pick up this feature request, personally I'd rather see this as a boost feature request. But there are certainly reasons why it has been dropped.

Regards
Wiebke

**Comment by HsH-Wolf** [comment]
To show the full name but also save the space for the menu, the name could be displayed on top of the user menu.

<img width="202" alt="BU_show_name" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/56588802/1f36332b-5633-4c64-b8bb-1db56a6650eb">
