### ISSUE TITLE
Release: Add contributors to README.md

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#44]
Before the release, it should be discussed if we should add all institutions who have funded contributions to this plugin to README.md

**Comment by lucaboesch** [comment]
BFH University of Applied Sciences, Luca Bösch: Code, Peer Review, Ideating
lern.link, Alexander Bias: Code, Peer Review, Ideating, Funding
University of Lübeck, Christian Wolters: Peer Review, Ideating
ZHAW Zurich University of Applied Sciences: Funding

**Comment by lucaboesch** [comment]
Maybe in a form (although it's kind of obvious), Moodle an Hochschulen e.V. should be mentioned, too.
Any idea on how to do this?
Or leave it away, since it's self-explaining?

**Comment by lucaboesch** [comment]
Additionnally, I would vote to leave the "Credits" section in

Credits

This theme is a successor of and heavily inspired by the former theme theme_boost_campus by Kathrin Osswald and Alexander Bias from Ulm University which was maintained until Moodle 3.11 on https://github.com/moodle-an-hochschulen/moodle-theme_boost_campus.

and only then add

Contributors

…
…
÷

**Comment by abias** [comment]
Hi Luca,

thanks for your numerous thoughts!

> I prefer "Contributors" over "Credits"

Yes, I agree with that and have changed the title of this issue accordingly.

> And I could imagine a specification of the work/contributions.

I agree with that as well!

> Maybe in a form (although it's kind of obvious), Moodle an Hochschulen e.V. should be mentioned, too.

I do not think that this is necessary as Moodle an Hochschulen e.V. is the publisher of this theme.

> Additionnally, I would vote to leave the "Credits" section in

Sure!

**Comment by abias** [comment]
As we approach a first release, I just went ahead and have added a 'contributors' section based on the discussion above to README.md in ccf327f.
