### ISSUE TITLE
Improvement: Allow for complete removal of the "footer" (question mark in circle) button

### ISSUE THREAD

**Issue by lucaboesch** [moodle-an-hochschulen/moodle-theme_boost_union#444]
In case you do not need it (because you have all your links elsewhere) there should be the possibility to remove the "footer"  (question mark in circle) right hand bottom button entirely.

<img width="368" alt="image" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/377279/f24faa80-ea25-4ad4-ac3e-efe0d0ec169a">

**Comment by wiebkemueller-hsh** [comment]
https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/6#issuecomment-1525411812

Hello Simeon, @moniNaydenov does this relate to the mentioning of Eva for PR in the issue linked above?

Regards
Wiebke

**Comment by ksteitz** [comment]
We completely turned off the in our eyes disleading question mark using "theme_boost_union | scss" and support Lucas proposal for an option to turn it entirely off. 
Here is our CSS: 

/*remove question mark button for footer*/
#page-footer button {
    display: none;
    visibility: hidden;
}
