### ISSUE TITLE
Feature: Add a password toggle icon on the login form

### ISSUE THREAD

**Issue by hribeir0** [moodle-an-hochschulen/moodle-theme_boost_union#458]
As discussed at the Global Moot, it could be interesting to have a password/text toggle on the login page. Do you think this makes sense?
If so, should it be added also with a setting?
I don't think I would be able to add a test for that, but I heard that Luca has fun coming up with those :)

**Comment by whuml** [comment]
also see discussion:
[https://moodle.org/mod/forum/discuss.php?d=430293](https://moodle.org/mod/forum/discuss.php?d=430293)

**Comment by abias** [comment]
Hi @hribeir0 ,

many thanks for proposing this improvement!

In the meantime, this feature landed in Moodle core 4.4 with [MDL-79769](https://tracker.moodle.org/browse/MDL-79769). It will be usabe in the upcoming 4.4 release of Boost Union as well, of course.

The only thing we could do is to backport it to Moodle 4.3 and even 4.1 within Boost Union - something which Boost core won't do. However, backporting core features is something which we haven't done before in Boost Union and should not start to do it from my point of view.

Against this background, I will close the issue for now.
