### ISSUE TITLE
Feature: Show a warning banner if JavaScript is disabled

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#46]
Moodle has been practicing progressive enhancement for years. However, it does not do this anymore. Even worse, it silently relies on JavaScript being enabled in the browser and does not output any notice if it is not. But if JavaScript _is_ disabled for any reasons, the user will have widgets which simply don't work.

I propose to add a warning banner which clearly tells the user to enable JavaScript if it is off.

**Comment by lucaboesch** [comment]
To be honest I find this a bit absurd.
Nowadays you pratically need a computer scientist's degree to disable javascript in a default browser, don't you think?
And then, i can assume, you should be able to forsee the consequences, shoudn't you?
But if you really want this, all right then.

**Comment by abias** [comment]
I agree that the standard user will never even think about disabling JavaScript in the browser. And you are right, it has become more difficult to disable JS as the browser vendors have moved the necessary switched to the back of the browser machine room.

However, please do not forget the advanced users who use browser extensions like NoScript (https://addons.mozilla.org/de/firefox/addon/noscript/) and who want to selectively enable JS on a per-site basis.

In the end, this was a request by one of our customers who told us that they _have_ such users and the actively want to inform them that JS is disabled.

**Comment by lucaboesch** [comment]
Done
