### ISSUE TITLE
Remembering of active boost union admin sub-tab after save and page reload

### ISSUE THREAD

**Issue by mwehr** [moodle-an-hochschulen/moodle-theme_boost_union#468]
If you change a value in the sub-tabs of the Boost Union Admin setting, the first tab is always selected after reloading the page and not the current tab in which the change was made.

It would be helpful if the current Boost Union sub-tab is opened again after saving and reloading the admin settings page.

**Comment by elz-hwr** [comment]
Functionally, the desired effect is achieved: after changing and saving a boost union value, the active setting bar remains open. 
Tested in version 4.3.2/4.3.3

No idea how important the following information is, but just to be on the safe side:
The following debug message occurred in both versions: 
```
user_preference_allow_ajax_update() is deprecated. Please use the "core_user/repository" module instead.

    line 41 of /lib/ajax/ajaxlib.php: call to debugging()
    line 59 of /theme/boost_union/layout/drawers.php: call to user_preference_allow_ajax_update()
    line 1486 of /lib/outputrenderers.php: call to include()
    line 1412 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 116 of /index.php: call to core_renderer->header()

user_preference_allow_ajax_update() is deprecated. Please use the "core_user/repository" module instead.

    line 41 of /lib/ajax/ajaxlib.php: call to debugging()
    line 60 of /theme/boost_union/layout/drawers.php: call to user_preference_allow_ajax_update()
    line 1486 of /lib/outputrenderers.php: call to include()
    line 1412 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 134 of /admin/settings.php: call to core_renderer->header()


Deprecated: Creation of dynamic property additionalregions::$regions is deprecated in /var/www/html/theme/boost_union/layout/includes/blockregions.php on line 50
```

**Comment by abias** [comment]
Thank you @elz-hwr  for testing the PR which belongs to this issue!
I think the deprecation warnings which you saw resulted from the fact that the PR is quite outdated and based on a Boost Union 4.1 release, but you tested it on 4.2 / 4.3 where user_preference_allow_ajax_update() was deprecated in Moodle core. No need to worry, I will take care of that during the review of the PR.
