### ISSUE TITLE
Upgrade: Boost Union unusable in the new site administration in Moodle 4.4

### ISSUE THREAD

**Issue by ralf-krause** [moodle-an-hochschulen/moodle-theme_boost_union#482]
Dear developers,
since today there is a new structure in the site administration of Moodle 4.4.

The design settings now can be opened with a settings button in the design chooser. The settings for Boost Union open only an error page "Bereichsfehler!"

Ralf

**Comment by lucaboesch** [comment]
That was caused by https://tracker.moodle.org/browse/MDL-78426

**Comment by abias** [comment]
Here's the corresponding debugging message: 

<img width="1440" alt="grafik" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/1092118/e403421b-5f14-48ff-9102-7ad32c245ad6">

**Comment by abias** [comment]
@ralf-krause - thank you for your patience. I just merged a patch which solves this fundamental problem on Moodle 4.4. You can give it a try if you use Boost Union from the master branch until Moodle 4.4 is officially out.

If you have the time to test-drive Boost Union on 4.4dev and spot any additional issues, please do not hesitate to create new issues for us.

**Comment by michael-milette** [comment]
@abias In case you didn't see it yet, this may have been fixed in 4.4 too. See:
https://tracker.moodle.org/browse/MDL-81512

Best regards,

Michael Milette

**Comment by lucaboesch** [comment]
That issue is not closed yet, @michael-milette.
Moodlers are invited to comment on https://tracker.moodle.org/browse/MDL-81512.
I think your opinion would be valued there, @abias.

**Comment by abias** [comment]
Thank you both.
I just added my 2 cents to the tracker issue.

**Comment by lucaboesch** [comment]
Thanks so much, Alex.

**Comment by lucaboesch** [comment]
Just noting that https://tracker.moodle.org/browse/MDL-81512 will be in Monday's 4.4 release. It is in "Tested" status now.
Not sure if it will be influencing Boost Union's handling of this, again.

**Comment by lucaboesch** [comment]
This can be closed.
https://tracker.moodle.org/browse/MDL-81512 is in, theme Boost Union in Moodle 4.4 is looking brilliant.
