### ISSUE TITLE
Smartmenus and own custommenuitems from past developments

### ISSUE THREAD

**Issue by benutzer-prog** [moodle-an-hochschulen/moodle-theme_boost_union#485]
I recently lost my own Custommenu developments due to the new Smartmenus. How can I continue to use my code such as " $CFG->custommenuitems .= $quickmenu;" in conjunction with this theme so that these are also included in the Smartmenus?

**Comment by HsH-Wolf** [comment]
Dear @benutzer-prog, 

as there was no further information, this issue will be closed. If you found a bug, please feel free to report it in a new issue. 

We offer a template for bug reports to give us all information we need in case of a bug.

Thank you on behalf of the Boost Union Team!
Yvonne

**Comment by benutzer-prog** [comment]
Dear Yvonne,

 many thanks, the last versions fixed the missing custommenus for me.

Bests,

Ben
