### ISSUE TITLE
Feature: Allow the admin to hide the manual login form

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#490]
On Moodle instances, where really all users are authenticated via a SSO backend like OIDC, the manual login form on the login page is not necessary and just distracts users.

It would be worthwhile to have an option in Boost Union to disable the manual login form completely.

**Comment by lucaboesch** [comment]
Fixed by #496.

**Comment by slaudel** [comment]
Just one question, how does the local admin get logged in(, in case something is broken with SSO)? I would like to use this on one instance of our moodle systems, but I need to login via manual login to use my admin account.

**Comment by abias** [comment]
Hi @slaudel ,

thank you for this comment!
I have split this into https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/539, I would be grateful if you could comment there.

**Comment by lucaboesch** [comment]
Note this has been re-taken up here https://tracker.moodle.org/browse/MDL-80967 for Moodle core.
I'm curious whether that will be accepted.
