### ISSUE TITLE
Class smartmenu_helper should use theme_boost_union namespace

### ISSUE THREAD

**Issue by lucaboesch** [moodle-an-hochschulen/moodle-theme_boost_union#494]
**Describe the bug**
If any other plugin or module wants to add a smartmenu_helper class that would clash

**To Reproduce**
Try to install a plugin with a smartmenu_helper class, run 
php admin/tool/behat/cli/init.php
and notice the 
Fatal error: Cannot declare class smartmenu_helper, because the name is already in use in … smartmenus/menulib.php on line 41

**Expected behavior**
If the class would have been called theme_boost_union_smartmenu_helper then it would have been all right

**Additional context**
I cloned theme_boost_union, renamed everything, e.g. to theme_luca and then tried to run Behat.

**Comment by abias** [comment]
This was solved in #498
