### ISSUE TITLE
Improvement: Reduce the code prechecks number in Moodle Plugin database again

### ISSUE THREAD

**Issue by lucaboesch** [moodle-an-hochschulen/moodle-theme_boost_union#497]
**Describe the bug**
As of now, there is a somewhat larger amount of warnings displayed in the Moodle Plugin database.
<img width="169" alt="image" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/377279/465d80d8-8f51-4c2f-b4d7-daf6e646cb41">

Some of them are easy to fix.

**Comment by abias** [comment]
I think I solved everything we can solve in 293cae5ca35b7119904c0b4c43ca93f7dae2113f - except the smart menu related warnings which will be handled in #362 / #508
