### ISSUE TITLE
Feature: Course related hints

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#5]
Boost Campus provides multiple course related hints feature. The documenation can be found on https://github.com/moodle-an-hochschulen/moodle-theme_boost_campus#course-related-hints.

There is these hints:
* Position of switch role information
* Show hint in hidden courses
* Show hint guest for access
* Show hint for self enrolment without enrolment key

All of these hints have proven to be useful in daily life and should be available for admins switching from Boost Campus to Boost Union.

However, this functionality does not necessarily have to be a part of a theme. It might be worthwhile to think about outsourcing the information banner feature into a plugin of its own.

**Comment by lucaboesch** [comment]
Just as an observation: the changed role which in Boost Campus was announced in a banner, now features near the logged in information in courses you have been switching it.

<img width="811" alt="loginas" src="https://user-images.githubusercontent.com/377279/164934028-7b7cfa73-1255-4c0b-a527-1b683d504b96.png">

It could be worthwhile deliberating of what else could be announced this way, in that place and what really deserves a banner.

**Comment by abias** [comment]
This feature was implemented and integrated in #27.

@lucaboesch - If you have any proposals with further refinements, I would appreciate if you would create another issue :)

**Comment by andremenrath** [comment]
This is very helpful, in the past even though we had a similar feature (Show hint in hidden courses) in our theme, some teachers still believed that creating a new topic in the notifications forum would trigger mail notifications. It might seem nitpicky, but adding a warning automatically via `showhintcoursehidden` also on the forum page might be of use from time to time. Pull Request would be kind of ready, if you are interested.
