### ISSUE TITLE
Release: Add note to theme_boost_campus about Boost Union

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#50]
As soon as Boost Union is officially released in the Moodle plugin repository, we should add a note to https://moodle.org/plugins/theme_boost_campus and https://github.com/moodle-an-hochschulen/moodle-theme_boost_campus highlighting the fact that Boost Campus won't be released for 4.x and that Boost Union is the successor.

**Comment by abias** [comment]
As it stands now, there is a big note on https://moodle.org/plugins/theme_boost_campus pointing to Boost Union and the "About" text on https://github.com/moodle-an-hochschulen/moodle-theme_boost_campus has been modified as well.

**Comment by ksteitz** [comment]
Very well, the red box looks much better than the info text i added some months ago at moodle.org.
