### ISSUE TITLE
block region content-upper (and similar) - option to display as cards

### ISSUE THREAD

**Issue by MURBASLMS** [moodle-an-hochschulen/moodle-theme_boost_union#502]
We use content upper region in a course just for teacher admin type blocks, currently an activation date and status block we have, but i could see this region being useful to have info you'd want up and front on the main course page view. Currently the blocks display as full content width but it would be good for this to be able to be displayed as cards to reduce the vertical space on desktop. I see you have display options for the outside regions so wondered if something similar could be extended for the content type regions?

**Comment by whuml** [comment]
Hi @MURBASLMS ,
thank you for your "impovement" request for our "Additional block regions". 

As far as I understand your comment you'd like to see 
additional block regions for 'course' layout 
- "Content (upper, left)"
- "Content (upper, center)"
- "Content (upper, right)"

and for Content lower region...

I'm setting Label "discussion needed" as this improvement might be useful for some usecaseas but "... too many block regions could overwhelm end users ..." and admins -> to be discussed.

So "stay tuned" :-) and
brgds on behalf of Boost Union Team
Wolfgang

**Comment by wiebkemueller-hsh** [comment]
Hi @MURBASLMS ,

additionally to what Wolfgang said I would like to point you to the options that Bootstrap Cards give you in the course content display. Have you already considered this? https://getbootstrap.com/docs/4.3/components/card/ We're using it quite frequently and it's not too complicated.

Best regards
Wiebke

**Comment by wiebkemueller-hsh** [comment]
Hi @MURBASLMS we've discussed this requirement with the team and we're sorry to inform you that for now we won't consider any more block regions within the course layout and would like to invite you to make use of the bootstrap cards. In case you'd like an example or some template code please get in touch. Regards Wiebke

**Comment by MURBASLMS** [comment]
ok fair enough, yep i'm familiar with boostrap cards, also use them a lot, however that is not what i meant with this, we "deploy" blocks to particular regions and that upper content area is potentially useful to us but not so much in the way it's currently designed. cheers for considering though.
