### ISSUE TITLE
Allow administrators to change the order of login items on the login page without using CSS or touching the mustache template

### ISSUE THREAD

**Issue by slaudel** [moodle-an-hochschulen/moodle-theme_boost_union#504]
For our login page, we adjusted the order of (login) options/elements in the Moodle Core login mustache template.

First we want to show the login instructions and then the list of IdPs for SSO. Then the login form for local registration and finally the guest login button.
![bildschirmfoto-2023-09-13-um-08-29-32](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/1032256/24b18fbc-7e9c-4a43-a646-a2f63e5afb98)

Unfortunately, the issues #473 and #490 cause our customization in core to be ignored and the default order to be used.

Hence my suggestion: It should be possible for administrators to configure the order of items in the menu without having to resort to “hacks” or CSS.

**Comment by wiebkemueller-hsh** [comment]
I'd like to add a few thoughts from Sévérin, considering the display. Maybe this could be included when touching the feature? I'd think of some visual hierarchy between methods. For admins to set method A to be the most prominent would then mean, listed on top but also displayed bigger? If this need design input, maybe @HsH-Wolf could work something out.

Citation from [](https://moodle.org/mod/forum/discuss.php?d=453681#p1826322)
"In my changes in mustache, i also inserted more spaces between the SSO and the other authentication methods, and some elements where displayed bigger (or the opposite), to make SSO (CAS for us) more proeminent, and the rest usable, but well separated."

**Comment by wiebkemueller-hsh** [comment]
#332 also addressed this issue and was closed as duplicate.

**Comment by abias** [comment]
I just pushed PR #564 which allows the admin to define the order of the login methods in the login form. It does this with CSS flexbox which was easier to accomplish than reordering the HTML in the DOM (and it still fully working on modern browsers).

PR #564 also allows the admin to add a intro line saying "Login with your Moodle account" to the local login method in the login method if necessary. This is especially helpful if the local login method is not the first login method anymore.

Regarding the proposal of being able to customize the font sizes and other visual weights in the login form: I didn't want to piggyback this to the pure re-ordering.

Please don't hesitate to create a new issue with a clear vision what should be configurable, ideally with some mockups.
