### ISSUE TITLE
Can't update even though all dependencies are met

### ISSUE THREAD

**Issue by VOOM108** [moodle-an-hochschulen/moodle-theme_boost_union#552]
**Describe the bug**
Trying to install v4.1-r18 on Moodle 4.1+ (Build: 20221209) All dependencies should be met, but I cannot install the version for 4.1. The version for Moodle 4.0 works, but has less features. 

**Screenshots**
<img width="961" alt="image" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/16562946/70671d1a-8418-4748-aecd-11cde9f7ecdf">

![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/16562946/f325ff9a-06c4-4683-af2d-f6cb8b97b34c)

Here it looks like the Moodle Version 401 is wrong, at another time the error badge was next to the boost version. I tried to trick it by changing the dependencies in the version.php to see what happens, but it does not make a difference. 

What could be causing this, if the dependencies actually are met?

**Comment by VOOM108** [comment]
Hi! I have upgraded to the newest Moodle 4.1.8+ today and the dependency-check still fails for v4.1-r18

**Comment by VOOM108** [comment]
Now it worked, after I had to correct some other errors :))

**Comment by lucaboesch** [comment]
Excellent. Glad to hear.
