### ISSUE TITLE
Configure order of auth methods

### ISSUE THREAD

**Issue by HoffmannP** [moodle-an-hochschulen/moodle-theme_boost_union#569]
**Is your feature request related to a problem? Please describe.**
Different institutions non only have different authorization methods but they also differ in their order. To account for that it would be nice to configure the order of auth methods on the login page without needing to manually change the template.

**Describe the solution you'd like**
Most users should be able to login with the first method
As an administrator I want to configure the priority of authorization methods.

**Describe alternatives you've considered**
Changeing the template

**Comment by lucaboesch** [comment]
I believe this is #504, @HoffmannP.
If so, it has already been coded and integrated. Hang on to the next release.

**Comment by abias** [comment]
Yes, I think this is already solved by #504. I will close this as duplicate.

If you need anything else, please open a new issue and tell us what you are still missing :)

Cheers,
Alex
