### ISSUE TITLE
Hide an authorization method behind a second click

### ISSUE THREAD

**Issue by HoffmannP** [moodle-an-hochschulen/moodle-theme_boost_union#570]
**Is your feature request related to a problem? Please describe.**
To many auth methods on login (esp. yor local admin auth method)

**Describe the solution you'd like**
I don't confuse my users with auth methods they are not supposed to use
I let admins enable 2nd click for some auth methods.

**Describe alternatives you've considered**
Change the template

**Additional context**
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/432592/de35f832-d672-46b7-a7e3-157a1ea12a00)
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/432592/b77b5fdf-5ce8-4ee4-928f-976d03b9a1a6)

**Comment by abias** [comment]
This is a nice idea!

Just as a note:
We already have solved #504 and #539 recently which at least partly solves this proposal. And there is https://moodle.org/plugins/local_login which provides a different approach for the same problem.

**Comment by HoffmannP** [comment]
This was way to hacky anyways, hence I'd like to close this issue.
