### ISSUE TITLE
Smartmenu just for logged in user

### ISSUE THREAD

**Issue by create-martin** [moodle-an-hochschulen/moodle-theme_boost_union#571]
**Describe the bug**

Basically, I wanted to create a smartmenu that is visible for all logged in users (read: NOT on loginpage).

That seemed like an easy task, I restricted visibilty by role and set "Authenticated user":

![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/1061340/eb0d1c2e-152e-472c-9f68-b1310d42d3ef)

However, that hides the smartmenu completely? For logged in users, admin etc.

Am I missing smt obvious? 

I have smartmenus restricted by other roles (teacher, custom roles) and they behave exactly as expected.

**To Reproduce**
Just create a smartmenu, set role-restriction to "authenticated user" - and it's gone

**Expected behavior**
Should be visibly AFTER login (for everyone), but hidden on login-page

**Comment by create-martin** [comment]
Any update on that issue by any chance?

**Comment by abias** [comment]
@create-martin - sorry for the late reply. I hope that the fix which was just integrated into master will solve your problem.

**Comment by kaaermes** [comment]
Moodle 4.1.10 > OK
Moodle 4.2.7 > OK
