### ISSUE TITLE
Feature: Provide $CFG->themerev as SCSS variable

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#58]
During a custom SCSS design project, you might come into the situation that you have to link to a uploaded image or other asset which is served by Moodle's pluginfile.php script. Unfortunately, these URLs contain a theme revision parameter.

To be able to use these URLs properly in custom SCSS and to avoid breaking Moodle's caching features, it would be helpful to have the content of $CFG->themerev available in a SCSS variable.

**Comment by lucaboesch** [comment]
Fixed by #533.
