### ISSUE TITLE
Feature: Add FontAwesome 5 or 6 to the theme

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#59]
Moodle core still ships with FontAwesome 4 which is really outdated. The discussion to upgrade FontAwesome to version 5 in https://tracker.moodle.org/browse/MDL-64853 was closed as "won't fix" and another discussion to move to ForkAwesome has been started in https://tracker.moodle.org/browse/MDL-67448.

Regardless of these core discussions, it would be awesome to be able to use FontAwesome 5 icons on sites with Boost Union out of the box, especially with the https://moodle.org/plugins/filter_fontawesome filter.

It would be worthwhile to check if it is technically possible and, regarding the FA license allowed, to add FontAwesome 5 Free to Boost Union. Additionally, it would be great if there would be a possibility to use the Pro icons as well if there is a valid FontAwesome license.

**Comment by ralf-krause** [comment]
Does this link help to answer your question? It seems to be allowed to host the FontAwesome 5 Free or FontAwesome 6 Free icons in Boost Union. For compatibility to the FontAwesome 4 icons in Moodle core you need to add some code. `In addition to whatever v6 CSS files you're including, you'll want to include the following v4-shims.js file, which will map v4 icon names to icons in the latest version of Font Awesome.`

**Comment by ralf-krause** [comment]
Moodle closed the https://tracker.moodle.org/browse/MDL-64853 to implement ForkAwesome. In the FontAwesome 5 Free and FontAwesome 6 Free version there are missing a lot of icons.

**Comment by abias** [comment]
This has been solved by #141 now
