### ISSUE TITLE
Feature: A real footer

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#6]
Moodle 4.x radically reduced the footer to a single floating question mark icon. After clicking on the question mark icon, users just see some links which used to be in the Moodle page footer before in Moodle 3.x

Institutions might need a real footer with
* The possibility to place reliable and directly visible links to the imprint, to data protection rules and user policies.
* The possibility to add some footer blocks to each page
* The possibility to hide / get rid of some or all standard links which Moodle places in the footer (or the question mark icon on Moodle 4.x)
* The possibility to show some images like badges in the footer of the page

Boost Campus already did this. The documentation can be found in 
https://github.com/moodle-an-hochschulen/moodle-theme_boost_campus#4-tab-footer-layout-settings
https://github.com/moodle-an-hochschulen/moodle-theme_boost_campus#image-area
https://github.com/moodle-an-hochschulen/moodle-theme_boost_campus#footnote.

However, there is the need to rethink footers for Boost Union.

**Comment by abias** [comment]
In #20, the footnote was added to Boost Union. 
However, the other aspects remain open.

**Comment by MURBASLMS** [comment]
Just being able to easily add a static footer for institution logo, links inc privacy and other things we need to display would be very good with this theme (which is asweome btw). I've always had to customise themes locally to do it properly. 

eg
<img width="1346" alt="Dashboard_and_Feature__A_real_footer_·_Issue__6_·_moodle-an-hochschulen_moodle-theme_boost_union" src="https://user-images.githubusercontent.com/83204517/232173111-752614cb-6c28-46a5-92e8-ae8359a07225.png">

**Comment by wiebkemueller-hsh** [comment]
Hi @abias or @lucaboesch , 

do we get it right that this issue proposes a possiblity to get totally get rid off the of the "question-mark-footer" and not just alter its content? 

Regards&Grüße 
Wiebke und Yvonne

**Comment by goggo24** [comment]
Hey all,

we've also found the question mark annoying, respectively we don't know at the moment, how to cope with contextual help. So our first solution was an adminsetting, which controls only the visibility:

![grafik](https://user-images.githubusercontent.com/16721900/234836013-2ed6081b-f6f8-4ca3-a8cd-246f4a8744d6.png)

If there is interest in this implementation, we can add an PR in the next weeks.

Regards, Eva K. (AMC)

**Comment by lucaboesch** [comment]
That would be lovely, @goggo24 !
It's one reason I maintain a fork of Boost Union.

**Comment by snowlord78** [comment]
Hey @goggo24 ,

this would be a nice function.

**Comment by abias** [comment]
I have pushed another PR #532 to get this issue finally done.

**Comment by abias** [comment]
I will close this now as #532 was merged
