### ISSUE TITLE
Improvement: Signal new never visited courses

### ISSUE THREAD

**Issue by cdipe** [moodle-an-hochschulen/moodle-theme_boost_union#601]
**Is your feature request related to a problem? Please describe.**
A problem is to get notified about new courses that one has been added to (in different ways of adding users) and has access to. It's easy that already starred courses get all attention.

**Describe the solution you'd like**
As a user, I would like a new course that I have access to but haven't visited yet to show highest up in my **Courses** list, first in the **Last visited courses** block and highest up in the Boost Union star marked courses quick menu. Preferably with something marking it as "New course". Once visited, the new course should be treated as any of my courses.

**Describe alternatives you've considered**

**Additional context**

**Comment by whuml** [comment]
Hi @cdipe 

this is what I get, when sorting "course overview" by "last accessed".
Courses never visited are shown at the very end of the list...
From my point of view it should be a moodle core issue to provide course lists that can be sorted "down to top".

Brgds
Wolfgang

**Comment by whuml** [comment]
Hallo @cdipe 

we discussed this in the planning team today. 
Definitly this is out of scope for theme development and has to be addressed in the tracker/core to be realized (in an extra plugin).

Thanks for your contribution anyhow!

Brgds
Wolfgang

**Comment by cdipe** [comment]
@whuml  I understand. I have added this as an improvement suggestion and with mockups in the tracker, https://tracker.moodle.org/browse/MDL-81438
