### ISSUE TITLE
Smart menu: Menu bar overlays course index

### ISSUE THREAD

**Issue by HsH-Wolf** [moodle-an-hochschulen/moodle-theme_boost_union#607]
If I place a menu in the menu bar, the menu bar appears which leads to an overlay of the course index so the first link in the coure index is not visible anymore.

**Steps to reproduce**
- As an admin create a smart menu
- Choose to display the smart menu in the menu bar
- Go to a course (and open the couse index)

<img width="620" alt="Course_Index_Overlay" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/56588802/87969d7c-96be-4faf-8de4-be2d6faa1582">

**Comment by kaaermes** [comment]
1. As an admin create a smart menu
2. Choose to display the smart menu in the menu bar
3. Go to a course (and open the couse index)

**Moodle 4.2.7 > OK**

<img width="629" alt="Bildschirmfoto 2024-05-13 um 13 34 02" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/128585815/c28f847c-9195-4417-bef4-0ae46fb891bc">

**Moodle 4.1.10 > OK**

<img width="629" alt="Bildschirmfoto 2024-05-13 um 13 45 16" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/128585815/a991492e-9b29-484d-9730-46c72185b865">
