### ISSUE TITLE
add additional bootstrap colors via moodle admin GUI 

### ISSUE THREAD

**Issue by a-kempka** [moodle-an-hochschulen/moodle-theme_boost_union#608]
I would like to provide additional colors to moodle in a controlled manner. The colors should be available in many (bootstrap-)components without the need of extensive color declarations (for shading, different states). Bootstrap can be customized to allow additional colors - the color variants and colors for the components (like ``btn``) are generated automatically. (See https://stackoverflow.com/questions/8596794/customizing-bootstrap-css-template/50410667#50410667) 
Currently I can only modify existing colors (primary, secondary etc.) in boost union (e.g. ``theme_boost_union | bootstrapcolorsuccess``), not add new colors.

**Describe the solution you'd like**
  - As an admin I would like to set up additional colors for bootstrap in the boost union gui without having to modify .scss files or the theme's prescss in ``theme_boost_union | scsspre``. I would like to give the users access to bootstrap's components (e.g. ``btn``) in a expanded variety of curated colors (e.g. ``btn-fancycolor``), where variants of the colors are provided by bootstrap (e.g. for active, disabled, outline buttons, etc., such as ``btn btn-outline-fancycolor``). 
  - As a teacher I would like to use additional colors (e.g. seperate colors for widgets/buttons/links etc. in faculties) with less hassle. The preset classes for additional colors could be provided as atto style settings or other equivalents.

**Describe alternatives you've considered**
 - It is possible to modify the bootstrap's ``_variables.scss`` (https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L75) or set a prescss ``theme_boost_union | scsspre`` and declare variables there. However this means additional maintenance when upgrading and it is less flexible and more error prone to add colors as system files have to be changed or the prescss has to be injected which can lead to unexpected things.

**Additional context**
For the gui the settings could be used in a similar manner to ``theme_boost_union | bootstrapcolorsuccess``
 - after the customization of the bootstrap colors (primary, secondary, ...) place a button to add a new color
 - provide a label to name the additional color / the class, prevent users from choosing internal names (primary, secondary, ...)
 - provide a button to remove the color, if not needed anymore

**Comment by whuml** [comment]
hi @a-kempka,

thanks for your colorful idea :-)
seems to be a good improvement to provide additional Bootstrap "color utility classes". 
Could imagine to provide functionality like "theme_boost_union | bootstrapcolorxxxx"
and assingn it within Boost Union for example to infobanners "theme_boost_union | infobanner1bsclass".
But at least
to provide these classes (with Boost Union functionalities) by editors like atto or tinymce needs to be discussed with Developers and the team... 
_" .. could be provided as atto style settings or other equivalents. "_ = separate Plugin

brgds
Wolfgang
