### ISSUE TITLE
Add activity purpose "Interactive content" for Moodle ≥ 4.4

### ISSUE THREAD

**Issue by lucaboesch** [moodle-an-hochschulen/moodle-theme_boost_union#611]
[MDL-78284](https://tracker.moodle.org/browse/MDL-78284) introduced "Interactive content" MOD_PURPOSE_INTERACTIVECONTENT as purpose.
This should be added e.g. in the settings for 'Activity icon purposes'.

**Comment by abias** [comment]
Hi all,

this issue has now been fixed for Moodl 4.4 in be8942eef74b955343c7cfb94067420800b3d0cc.
This commit is located in the [upgrade-404](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/commits/upgrade-404/) branch which will be merged in the main branch as soon as the whole Moodle 4.4 upgrade work is done.

Cheers
Alex
