### ISSUE TITLE
Fontawesome 6 seems broken in 4.1

### ISSUE THREAD

**Issue by MURBASLMS** [moodle-an-hochschulen/moodle-theme_boost_union#624]
Hello, 

on mdl4.1 commit 43042fce7cce692e1cef327c76051f5965c1d81d, just updated and i noticed FA6 functionality not working now. It was before with all the relevant files installed. Ticks in the right places, apart from the checks at the bottom now which don't show the fa6 any longer. using fa filter which is up to date.

thanks

**Comment by abias** [comment]
Hi @MURBASLMS ,

thank you very much for reporting this issue.

This is a regression in the last release within ee614ab9642c76dd6c790652f88bb4ba33c1ae6b where I unfortunately missed the difference between 4.1 and 4.2 during the backport process.

I will handle and fix this instantly.

Cheers,
Alex

**Comment by MURBASLMS** [comment]
thanks for that, all good now
