### ISSUE TITLE
When viewing a single section, course header is not displayed

### ISSUE THREAD

**Issue by monnardj** [moodle-an-hochschulen/moodle-theme_boost_union#638]
In Moodle 4.4, clicking on a section title displays only the corresponding section (this is a standard feature which cannot be disabled). With theme boost, the course breadcrumbs are always displayed, which allows the user to click on the course name to go back to the course page with all sections displayed :

<img width="584" alt="image" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/5880250/84c38467-7a46-4256-88a1-b4622948224a">

But with boost_union, the breadcrumbs are not shown in single section mode, which makes it impossible to go back to the course home page :

<img width="594" alt="image" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/5880250/6cec85c2-fb70-4ac4-b27b-19ecc1f121e7">

The course breadcrumbs only appears if option"Display the category breadcrumbs in the course header" is enabled, which should not be necessary.

**Comment by abias** [comment]
Hi all,

this issue has now been fixed for Moodl 4.4 in 06dc95e472298e212d7a1144082a50c7eff53fe3.
This commit is located in the [upgrade-404](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/commits/upgrade-404/) branch which will be merged in the main branch as soon as the whole Moodle 4.4 upgrade work is done.

Cheers
Alex
