### ISSUE TITLE
Boost Union - RTL - Kebab menus are overlapped by the block drawer

### ISSUE THREAD

**Issue by acquaalta** [moodle-an-hochschulen/moodle-theme_boost_union#651]
Hi,
Moodle version: 4.3.3
Plugin version: v4.3-r12 (2023102035)

When the block drawer is opened in a course main page, and while being in edit mode, kebab menus (of activities/resources, for example) are at least partially overlapped by the block drawer. Please note that the bug would appear only when there is not enough space between the content in the main page and between the block drawer, for example when the browser window is in small.
**Please note that repro steps below refer to the course main page, but it seems that the bug appears in other pages as well.**

**Repro Steps**
1. Change the UI language of Moodle to an RTL language, like Arabic or Hebrew.
2. Go to a course main page
3. Switch to edit mode.
4. Click the kebab menu of an item (activity/resource)

**Expected behavior**
In Right-to-left (RTL) mode, the kebab menu should be opened to the right. In LTR mode, the kebab menus in the course main page are opened to the left, so this behavior should be mirrored in RTL mode.

**Actual behavior**
In Right-to-left (RTL) mode, the kebab menu is opened to the left, and then part of it is overlapped by the course block drawer.

**Screenshots**
![BU_RTL_KebabMenu](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/51836675/f18f35af-9cd0-4c19-9ad7-85a89e1f70b4)

**Comment by wiebkemueller-hsh** [comment]
Hi @acquaalta have you had a chance to test this on a plain moodle boost core site with moodle 4.4? E.g. https://sandbox.moodledemo.net/ Is it a boost union specific bug? Regards Wiebke

**Comment by wiebkemueller-hsh** [comment]
Hi @acquaalta we've been able to reproduce this on the sandbox. It is a bug but this would have to be reported to the moodle tracker. I'd say the context menu best has to open in the other direction to fix the problem. You can also test this here https://sandbox.moodledemo.net/ 
Best regards, Wiebke

![grafik](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/72548805/5561d42f-ee1d-4270-9ff0-15acec2fbb50)

**Comment by acquaalta** [comment]
@wiebkemueller-hsh You're absolutly right :-)
I assume that I didn't believe that such an issue wasn't noticed during the QA of Moodle (with the default theme Boost), that I decided automatically, without verifying it, that it's a Boost Union issue.
I'm sorry for the confusion.
