### ISSUE TITLE
Footer displacement on pages with minimal content

### ISSUE THREAD

**Issue by Sebbsen** [moodle-an-hochschulen/moodle-theme_boost_union#655]
**Describe the bug**
The footer does not stay at the bottom of the screen when there isn't enough content on the page to fill the viewport. This bug has previously occurred [#269](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/269) and was fixed [#309](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/309#issue-1756341360), but it has reappeared, likely due to a recent update.

**To Reproduce**
1. Go to or create a page with minimal content.
2. Observe that the footer does not stick to the bottom of the viewport but moves up, leaving a gap beneath it.

**Expected behavior**
The footer should remain at the bottom of the screen, regardless of the amount of content on the page.

**Screenshots**
_The footer contains only "Lorem Ipsum" as placeholder text._
_Screen size is is 1920x1080_

![footer-bug](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/33844473/f006e3ad-d3db-41be-a20f-f49a8bae05bb)

**Desktop:**
 - OS: MacOs 14.0 (23A344)
 - Browser: Chrome
 - Version: 124.0.6367.119

**Comment by whuml** [comment]
Hallo @Sebbsen 

thanks for posting this issue.
I recogized same bahaviour at core Moodle at their https://sandbox.moodledemo.net/ .
As we already fixed it at boost union #269  and #309 I added our "bug" label for fixing that with boost union again.

brgds
Wolfgang

**Comment by LisaE14** [comment]
We have the same problem. When can we expect it to be fixed?

**Comment by Menrath** [comment]
> As we already fixed it at boost union #269 and #309 I added our "bug" label for fixing that with boost union again.

#309 added the `flex: 1 0 auto;` to the `main-inner-wrapper` CSS-class. Seems like this is not enough anymore, the element with the id `page` (and maybe also `page-wrapper`) need this as well:

```css
 #page-wrapper #page {
    flex: 1 0 auto;
}
```
