### ISSUE TITLE
Display footer block regions on home page for non-logged-in users

### ISSUE THREAD

**Issue by Sebbsen** [moodle-an-hochschulen/moodle-theme_boost_union#660]
**Describe the bug**
The block region footer is currently only visible to logged-in users. There is a request to enable the visibility of these blocks on the home page for non-logged-in users as well.

**To Reproduce**
1. Enable additional block regions for 'frontpage' layout (Footer)
2. Add Blocks to footer regions
3. Logout
4. Observe that the blocks are not visible.

**Expected behavior**
It is expected that the footer block regions blocks should be configurable to be visible on the home page for non-logged-in users, similar to how they are visible for logged-in users.

**Screenshots**
logged-in user
<img width="1241" alt="Screenshot 2024-05-19 at 12 35 58" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/33844473/51dacf13-19e6-4691-bf55-d8862ba06de3">

non-logged-in user
<img width="1255" alt="Screenshot 2024-05-19 at 12 35 38" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/33844473/6bacbb0e-f89d-45ab-b606-76d70702be55">

**Comment by taowang1993** [comment]
Other blocks have the same issue, even after adding "Guest" to permissions.

**Comment by whuml** [comment]
Hallo @Sebbsen 

as I tried to reproduce your Issue:
at the Boost Unions description for "Additional block regions" I found 

"...  As soon as an additional block region is enabled, it is visible for all authenticated users  ... But there are also theme/boost_union:viewregion* and theme/boost_union:editregion* capabilities which allow you to fine-tune the usage of each block region according to your needs."

This is what I tested then. I adjusted the capability setting for my specific start page role setting. For example changed "theme/boost_union:viewregionfootercenter" to "allow" for Guests - et voila - my Block at that region was visible for not logged in Guests.

At that stage I would say that there is no bug - it works as described :-)

Pls try and send me your feedback.

Brgds
Wolfgang

**Comment by taowang1993** [comment]
> theme/boost_union:viewregionfootercenter

Thank you!!!! This really helps!!! 

The role setting is too long. I didn't even look at it.

For future people, navigate to site admin > users > define roles > guest (click on the settings icon)
Then press Control + F to search: boost_union:view
You can unlock all "view" to show the blocks to guest users.

**Comment by Sebbsen** [comment]
@whuml Thank you for your help! I adjusted the settings as described, and now everything works perfectly.

**Comment by whuml** [comment]
@Sebbsen , @taowang1993 
thanks for your positive replies :-)
