### ISSUE TITLE
Give URL link possibility to a level 1 item of the smart menu

### ISSUE THREAD

**Issue by Lesgever** [moodle-an-hochschulen/moodle-theme_boost_union#661]
Could it be possible to give a URL in smart menu items of level 1 (main menu) and also the same settings (roles and cohorts) as the menu items of level 2 (submenu)? Now menu items that link to a URL must always be a sub-item.

**Comment by whuml** [comment]
Hi @Lesgever 
Link to URL is already possible.
Pls read forums diskussion ["Moodle in English: Boost Union Questions"](https://moodle.org/mod/forum/discuss.php?d=452129#p1843071) were Yvonne shows how to activate.
There is described what you wanted !?

Rgds
Wolfgang

**Comment by Lesgever** [comment]
https://moodle.org/mod/forum/discuss.php?d=452129#p1843071
