### ISSUE TITLE
Smart menus: boost union admin doesn't display existing menu, throws session error

### ISSUE THREAD

**Issue by MURBASLMS** [moodle-an-hochschulen/moodle-theme_boost_union#666]
Hi, i haven't fiddled much with smart menus but am interested in rolling them out sometime. I found that when i created one for the main nav (basic settings to show a submenu list for a system staff role), it displays ok outside of theme admin eg dashboard context, but now i can't edit it or add another one - it throws a session error when i save a new one. 

The nav menu doesn't display at all while in theme admin. when i go to add a new smart menu there is a message about not being able to display the draft version of the description. 

    line 85 of /lib/sessionlib.php: moodle_exception thrown
    line 42 of /theme/boost_union/smartmenus/edit.php: call to require_sesskey()

is all i can see in debugging. have cleared caches, session, logged in again etc.

MDL 4.1.10+ (Build: 20240530)
latest MOODLE_401_STABLE boost union.

**Comment by whuml** [comment]
Hi @MURBASLMS 
we are note sure what you mean with "outside of theme admin". Does it mean not logged in as admin or not in the admin setting or ...?

Could you pls try to describe more detailed or/and add some screenshots?

Thanks for clarification and best regards
Wolfgang

**Comment by MURBASLMS** [comment]
sorry, not the first time i've been vague :) 

i mean not in theme settings pages. i'm logged in as admin, i set up a smart menu, added an item, went back to dashboard, it appeared in the top nav menu as configured. Went back to add another item and in the theme smart menu page there is nothing set up. I go to add another one and it throws a session error and won't let me save anything. I go back to dashboard and the original menu is still there. 

![Dashboard___MyMurdoch_Learning](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/83204517/2f8ca551-5332-4c01-9889-48906efd7ae9)

**Comment by MURBASLMS** [comment]
... however, NOW the smart menu is there, after another login perhaps (although i had already done that the other day, cleared sessions, cache etc) - however it is failing in a similar way, in that, i go to add another menu item, that works, i go back to the dashboard, it appears ok, go back to theme settings for smart menu and the item i just added isn't there in the list of items in the smart menu i just edited. 
<img width="1079" alt="MyMurdoch_Learning__Administration__Appearance__Themes__Boost_Union__Smart_menus___MyMurdoch_Learning" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/83204517/f0f8f43b-da96-4fb5-9252-b44acba1c1f2">

<img width="960" alt="Dashboard___MyMurdoch_Learning" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/83204517/815b8da7-7472-4597-b00b-c9d33dd35bcf">

**Comment by HsH-Wolf** [comment]
Dear @MURBASLMS 

I tried to reproduce this behaviour, but for me everything works fine.
Could you please provide a detailed step by step describtion (or maybe a screencast) to reproduce this behaviuor.
If it is possible, please try to reproduce it in an "empty" moodle to exclude side effects from other settings or plugins.

Best regards in behalf of the boost union team
Yvonne

**Comment by MURBASLMS** [comment]
no worries, will test some more, thanks for looking. 

It's just odd that it seems related to the session getting lost each time, not that sure what other plugin or setting would be conflicting.

**Comment by MURBASLMS** [comment]
<img width="1100" alt="Cursor_and_Developer_Tools_—_MyMurdoch_Learning__Administration__Appearance__Themes__Boost_Union__Smart_menus___MyMurdoch_Learning_—_https___lmsapppre_murdoch_edu_au_theme_boost_union_smartmenus_edit_items_php_menu_2_sesskey_YmDfDbn3g9" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/83204517/8ee587d6-271a-48c5-9c5f-ee635b3b3fa7">

not sure if it helps, but i get a heap of these js errors when i go to add a smart menu item.

**Comment by MURBASLMS** [comment]
found the issue. is related to our set up. we use varnish which seems like it is caching the items.php page. It was likely caching the page content before the new menu item was added, resulting in the changes not being reflected.

**Comment by lucaboesch** [comment]
Great, thanks a lot!
