### ISSUE TITLE
Blocks navigation and administration

### ISSUE THREAD

**Issue by ralf-krause** [moodle-an-hochschulen/moodle-theme_boost_union#67]
Hi,
I found the blocks navigation and administration in the block drawer. Is this correct? Is this an issue or a feature? How can I disable this feature if I don‘t want to have these oldfashioned blocks? Moodle 4.0 has changed the navigation and the administration.

Best regards,
Ralf

Ralf Krause
moodleSCHULE e.V.

**Comment by abias** [comment]
Thanks, Ralf.
We will investigate if this is a regression which is introduced by Boost Union or what's happening here.

**Comment by abias** [comment]
Hi Ralf, 

thanks for reporting this issue. This was a glitch in my work which was just solved by Luca in #87.

Cheers,
Alex
