### ISSUE TITLE
Change order of menu items in Smart menu

### ISSUE THREAD

**Issue by Lesgever** [moodle-an-hochschulen/moodle-theme_boost_union#672]
**Describe the bug**
If you have a few items in smart menu and you want tot change the order it doesn't work always

**To Reproduce**
Make a few menu items an try to change the order

**Comment by HsH-Wolf** [comment]
Dear @Lesgever 

I tried to reproduce this behaviour, but for me everything works fine.
Could you please provide your moodle and boost union version and a detailed step by step describtion to reproduce this behaviuor.

Best regards in behalf of the boost union team
Yvonne

**Comment by Lesgever** [comment]
Hallo,
thx for the tip. It was a version problem.
In the latest version of Moodle 4.4+ and Boost union v4.3-r13 this works well

**Comment by HsH-Wolf** [comment]
Hello @Lesgever 
Thank you for your feedback
