### ISSUE TITLE
Feature: Back to top button

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#7]
Moodle 4.x got rid of the "Back to top button". The fact why this was done is briefly noted in https://docs.moodle.org/dev/Moodle_4.0_developer_update#Removal_of_back_to_top_link.

However, some institutions might still need want to have a "Back to top" button for some reason.

It would be quite easy to add an admin setting to Boost Union to provide a "Back to top" button again.

**Comment by tjettmers** [comment]
It is currently discussed as a possible solution for https://tracker.moodle.org/browse/MDL-74223, which actually belongs to https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/1

see https://www.figma.com/proto/0NPKDxZF1zEX7I0WQd1lyL/4.1-UX-LMS?page-id=2453%3A79730&node-id=4906%3A171779&viewport=16471%2C3465%2C0.65&scaling=min-zoom&starting-point-node-id=2522%3A72401

**Comment by abias** [comment]
I had a look at the mockup in MDL-74223 and have implemented what can be seen there in PR #31 .

If Moodle core ever add this back-to-top button back, the functionality can be removed again from Boost Union.
