### ISSUE TITLE
MDL-82158 removed /cache/classes/loaders.php, must be addressed otherwise.

### ISSUE THREAD

**Issue by lucaboesch** [moodle-an-hochschulen/moodle-theme_boost_union#708]
Since MDL-82158, the file /cache/classes/loaders.php required by classes/cache/loader.php does not exist any more.
The functionalities have to be embedded otherwise.

**Comment by ralf-krause** [comment]
Yes, this is a blocker for Boost Union in Moodle 4.5dev+ (20240829). 

Failed opening required '[dirroot]/cache/classes/loaders.php' (include_path='[dirroot]/lib/pear:.:/usr/share/php'). I found the include in the file theme/boost_union/classes/cache/loader.php

**Comment by abias** [comment]
Hi all,

thanks for raising this issue.
The Boost Union upgrade development for Moodle 4.5 will start this week and we will fix this fatal error as a first step.

Meanwhile, I would like to point to our Moodle release support rules on https://github.com/moodle-an-hochschulen/moodle-theme_boost_union?tab=readme-ov-file#moodle-release-support - Boost Union is maintained by volunteers who do not necessarily upgrade their sites directly after a new major version is released. Thank you for your understanding.

Cheers,
Alex

**Comment by ralf-krause** [comment]
Hi Alex,
sorry for sending a comment for this issue. 

Yes, I know (and I accept) that Boost Union does not run with Moodle 4.5 before you released your plugin for Moodle 4.5. But as you know I am a maintainer for the Moodle translation and I am testing all Moodle versions (the older ones and also the newest) with some plugins. And so I found that Boost Union was a blocker for an update of Moodle 4.5. I thought your were interested for issues and comments.

Yes, I like to use Boost Union in all my Moodle platforms. You are doing a great work with this plugin.

Best regards,
Ralf

**Comment by abias** [comment]
Hi @ralf-krause ,

no need to apologize at all. I am very grateful for your input and your insights.
Maybe comment above was too harsh and I am sorry about that. I just wanted to give a heads-up that we are aware of this issue and the development has started, but that Boost Union is not ready for 4.5 at the same day as the Moodle core release.

Coming back to the purpose of this issue:
@ziegenberg submitted a PR for this issue on #720 and I have just merged it into the upgrade-405 branch which is the basis for our Moodle 4.5 development. An official 4.5 release will follow after all remaining work is done.

Cheers,
Alex

**Comment by abias** [comment]
@ralf-krause - I see your point and have submitted another PR on #764 which should provide a more seamless upgrade experience.
