### ISSUE TITLE
Tiles format not respecting activity icon purposes

### ISSUE THREAD

**Issue by Jemma-Greener** [moodle-an-hochschulen/moodle-theme_boost_union#712]
Activity icon purposes are not being honoured when using tiles (https://moodle.org/plugins/format_tiles).

When you change the activity icon purpose in Boost Union, (e.g. questionnaire to collaboration), this is not reflected in the tiles plug-in format.

**Comment by wiebkemueller-hsh** [comment]
Hello @Jemma-Greener 
as to our understanding this is out of scope for BU development, could you report this with the tiles plugin? 
Regards
Wiebke

**Comment by Jemma-Greener** [comment]
No problem, the text on Boost Union said to report anything not working we will contact tiles.
