### ISSUE TITLE
Boost Union - Adding options to the course menus?

### ISSUE THREAD

**Issue by acquaalta** [moodle-an-hochschulen/moodle-theme_boost_union#716]
Hi,
Since I'm worried that's impossible because of Moodle limitations, I'll be concise in this feature request:
Is it possible for a theme (like Boost Union) to add menus and menus options to the course menus of Moodle?
I'm talking about the menu bar of "Course", "Settings", "Grades", "Reports", "More".

For example, let's say that I want that between "Reports" and "More", there will be another menu option, called "Bamboo" (which is a link to another screen), and after it there will be a menu called "Teacher Tools" and some menu options below it, in the menu.

**Comment by whuml** [comment]
HI @acquaalta,
 
Boost Union already is providing "smart menues" for main navigation with all your requested features.
With existing option to implement individual Menue Links within (text) blocks we shouldnt boost our theme with further "smart menues" at course level.
Sorry if we're not picking up your idea resp. feature request.
Thanks a lot and brgds

Wolfgang

**Comment by acquaalta** [comment]
@whuml Thanks a lot for the answer 😃
