### ISSUE TITLE
after_config hook callback should be migrated to new hook callback for core\hook\after_config

### ISSUE THREAD

**Issue by lucaboesch** [moodle-an-hochschulen/moodle-theme_boost_union#721]
If not modified, Moodle 4.5 would show the warning

`Callback after_config in theme_boost_union component should be migrated to new hook callback for core\hook\after_config`

**Comment by abias** [comment]
This was solved in 028d2cd5bcc2b30fad1e42602385617743cabec4

**Comment by abias** [comment]
I had to rework this solution. It is now solved in 4b2bc626e146d5d2dcfe9594134a6cb7daba000b

**Comment by abias** [comment]
Note: This solution will be backported into 4.4 in #735
