### ISSUE TITLE
Course Cards Configuration

### ISSUE THREAD

**Issue by mifantrax** [moodle-an-hochschulen/moodle-theme_boost_union#722]
**Is your feature request related to a problem? Please describe.**
Many times, professors teaching a course, especially with individualized plans, get lost in course dates, languages, and even course locations.

**Describe the solution you'd like**
As students or faculty view their Dashboard or home page, the card or list should contain elements that help them easily identify the course.

**Comment by wiebkemueller-hsh** [comment]
Hi @mifantrax 

there is a PR on the way which (I suppose) addresses your feature request. 

Please have a look here:
https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/555

Best regards
Wiebke

**Comment by wiebkemueller-hsh** [comment]
Hi @mifantrax 
we would like to point out that there is feature DashPro in Boost Union from @stefanscholz company BDecent, this addresses your feature request. We will therefore close this.
