### ISSUE TITLE
Improvement: Smart Menu - Restrict visibility by category

### ISSUE THREAD

**Issue by aguatacuperche** [moodle-an-hochschulen/moodle-theme_boost_union#723]
Hi.

The proposal is simple. It involves studying the possibility of adding a menu restriction by category (into "static" option). If it is done by cohorts, in some contexts, the menu must be reviewed every new school year. In this way, it is already fixed in time when students are promoted.

Thank you.

**Comment by wiebkemueller-hsh** [comment]
Hello @aguatacuperche 

thank you for the proposal, but we don't see this happening at the moment. The menu restrictions are tied to date or user related conditions and the course category is not user related in Moodle. 

Regards on behalf of the BU team
Wiebke
