### ISSUE TITLE
Adding awesom icon to main item in the navigation menu

### ISSUE THREAD

**Issue by Lesgever** [moodle-an-hochschulen/moodle-theme_boost_union#729]
It would be nice to have a field in the settings of the main menu items where we can choose an awesom icon, just like we do in the subitems
![Screenshot_1](https://github.com/user-attachments/assets/eb0874ad-9655-4c2b-8c3f-2e1abd1a126e)

**Comment by Lesgever** [comment]
Here is how I can add it on a subitem
![Screenshot_2](https://github.com/user-attachments/assets/ead721e7-d3da-4d15-986d-a0c4499e5f46)

**Comment by wiebkemueller-hsh** [comment]
duplicate with https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/673
#673
