### ISSUE TITLE
Hardcoded font and color for h2 and p

### ISSUE THREAD

**Issue by anna-sparkfore** [moodle-an-hochschulen/moodle-theme_boost_union#731]
**Describe the bug**
We're running theme_boost_union
v4.3-r16
2023102043
where the html tags h2 and p are hardcoded with Roboto font-family, a fixed font-size and color that conflicts with our preferred layout.

Maybe this is solved in newer versions?!

**To Reproduce**
1. Go to admin/settings.php?section=theme_boost_union_look#theme_boost_union_look_scss
2. See the header on the page which is blue
![image](https://github.com/user-attachments/assets/867921a9-1b31-4bef-8c0d-4eb96f32e2cb)

**Expected behavior**
The header should inherit the font-family, size and color from other stylesheets.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge Version 129.0.2792.89 (Official build) (64-bit)

**Comment by HsH-Wolf** [comment]
Hello @anna-sparkfore, 

I tried to reproduce this behaviour, but everything worked fine (also in Boost Union 4.3).

Did you apply your font to certain elements or to the whole body and could you please provide the CSS code you used? - e. g. 

```
body{
font-family: 'Barlow-Regular';
}
```

Best regard
Yvonne

**Comment by HsH-Wolf** [comment]
The style is not "hardcoded", for example you can apply your uploaded font only to h2 with this code:

<img width="541" alt="font-h2" src="https://github.com/user-attachments/assets/165e95b3-db5d-4397-93a6-d411d18dd909">
