### ISSUE TITLE
Improvement: Month names are always in english

### ISSUE THREAD

**Issue by ralf-krause** [moodle-an-hochschulen/moodle-theme_boost_union#75]
Hi,
in the info banner time settings the drop down menu always shows the english month names even I use the language "Deutsch (de)" or "Deutsch Kids (de_kids)". Also the numbers in the other drop down menus should have two digits ... with zero in front if there is only one digit.

Ralf Krause
moodleSCHULE e.V.

<img width="753" alt="Bildschirmfoto 2022-08-23 um 13 22 46" src="https://user-images.githubusercontent.com/27956839/186145910-2c1c723f-4093-4dda-88eb-57c143d27769.png">

**Comment by abias** [comment]
Thank you, Ralf, for reporting this issue.

I created PR #95 to solve this issue.

**Comment by lucaboesch** [comment]
This has been fixed with #94 

<img width="1137" alt="grafik" src="https://user-images.githubusercontent.com/377279/195444614-3b4d3fd6-7719-4641-8f4a-6e349e5fea55.png">
