### ISSUE TITLE
Feature Request: Teacher Course Header Images

### ISSUE THREAD

**Issue by buddy1234567** [moodle-an-hochschulen/moodle-theme_boost_union#77]
The Boost theme is nice and clean, minimalist in design and simplifies the end-user experience nicely.  Personalizing a course's appearance with a course header image can enhance a course's mood and help distinguish it from others.  Fordson incorporated this very nicely in moodle 3.x and our teachers really enjoyed this functionality as they felt it enhanced their course's uniqueness.

Example:
![class-mockup (1)](https://user-images.githubusercontent.com/34031812/187448279-e8a7db1d-a4ae-4092-85f6-d1b379415c22.jpg)

**Comment by dbnschools** [comment]
It would be awesome if you just took our code to implement this feature.  Boost union is a great theme and having this would make it more appealing to K-12 districts.  I am not the best at github but I could possibly create a pull request.

**Comment by lucaboesch** [comment]
Would this be possible with #118?

**Comment by abias** [comment]
> Would this be possible with https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/118?

Well, yes and no.

As soon as #118 will have landed, you will be able to add blocks to the places where the course image appears in @buddy1234567 's mockup.

However, you will need to place a block which displays the course image here.
This can either be achieved with a block_html instance together with https://moodle.org/plugins/filter_filtercodes. Or you can use an instance of Dash Pro (https://bdecent.de/product/dash-pro which is a paid premium plugin).

Anyway, as this wouldn't be straightforward, I would propose to leave this issue open and implement a dedicated Boost Union feature, ideally based on @dbnschools 's existing code.

**Comment by abias** [comment]
This was solved now by #170
