### ISSUE TITLE
Release: When Moodle 4.1 Boost Union is released, the favicon setting becomes obsolete

### ISSUE THREAD

**Issue by lucaboesch** [moodle-an-hochschulen/moodle-theme_boost_union#78]
With https://tracker.moodle.org/browse/MDL-75218 Moodle 4.1 receives that setting itself.
It should then be retired in Boost Union.

**Comment by arborrow** [comment]
Are there plans or a time line for the 4.1 release?

**Comment by abias** [comment]
> Now that Moodle 4.1 has been released, are there plans or a time line for the 4.1 release of the boost union theme?

@arborrow, thanks for asking.

Up to now, we know only of a minor issue of Boost Union on Moodle 4.1 and have, on the other hand, received several feedbacks that it works quite fine.

Regarding the official 4.1 release, we have started the upgrade process and would expect to release the release in about 2 weeks.

The upgrade is managed in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/199.

**Comment by arborrow** [comment]
@abias thanks for the reply and your work on the plugin, much appreciated!

**Comment by abias** [comment]
@lucaboesch , I had a look at this task here during the 4.1 upgrade. I could now remove the favicon setting from Boost Union and change the code which uses the favicon within Boost Union to pick it from the Moodle core upload.

However, I am tempted to leave the favicon upload within Boost Union and just add a clear note to the Boost Union settings that the favicon upload in Moodle core is ignored as soon as Boost Union is the active theme.

This is why:
* We have already added the possibility to override the favicon within a particular flavour. If we keep all the favicon picking logic and datastores within the theme, I expect life to be easier in the upcoming future.
* There is the issue #160 which asks to allow SVG logos. Unfortunately, the logo upload is limited to JPG and PNG in Moodle core. So, to realize #160 for Moodle 4.1 (and not in 4.2 in Moodle core at the earliest if anyone has the time to solve [MDL-61963](https://tracker.moodle.org/browse/MDL-61963)), I would have to move the logo upload to the theme. It does not make much sense to move the favicon upload out of the theme and move the logo upload into the theme at the same time.

What do you think? Can we just leave the favicon upload in the theme?

**Comment by lucaboesch** [comment]
I think this is a sensitive proposal, Alex.
Let's leave it in.
I'm closing this issue.

Best, Luca

**Comment by abias** [comment]
Thank you, Luca.

Based on this consensus and during the 4.1 upgade, I
1. added a notification to the branding settings to explain that there is still a dedicated favicon setting in Boost Union.
2. allowed other files than .ico and .png to be uploaded (like Moodle core does it now)
3. added the resizing feature to the favicon delivery (like Moodle core does it now)

This was done in 823d6faf02c04f1c0cd27a12f1745ce9005896a9.

And I created #217 where we can check if we can allow more than one favicon size to be uploaded.

**Comment by pjonker** [comment]
I installed your great theme on two Moodle LMS 4.1 sites. In both cases the favicon is not showing. It seems to be there because the Moodle standard favicon is gone but it leaves a blank area where the new favicon should be. Uploaded both an .ico and .png format.
