### ISSUE TITLE
From Moodle v4.5 to v4.5.1 = Blank Screen

### ISSUE THREAD

**Issue by caiadogithub** [moodle-an-hochschulen/moodle-theme_boost_union#787]
Hi,

After upgrading Moodle from **v4.5** to **v4.5.1**, I´ve got a **blank screen**. Only after deleting boost_union from server I´ve got te site back.

Info Boost Union:

$plugin->component = 'theme_boost_union';
$plugin->version = 2024100704;
$plugin->release = '**v4.5-r4**';
$plugin->requires = 2024100700;
$plugin->supported = [405, 405];
$plugin->maturity = MATURITY_STABLE;
$plugin->dependencies = ['theme_boost' => 2024100700];

Info Moodle:

$release = '**4.5.1** (Build: 20241209)'; // Human-friendly version name
$branch = '405'; // This version's branch.
$maturity = MATURITY_STABLE; // This version's maturity level.

Using Postgres 16, Ubuntu 24.04 & PHP 8.3.

Ricardo

**Comment by abias** [comment]
Hi @caiadogithub ,

thank you very much for raising this issue.
While I generally understand your problem, it's hard for us to trace down the source of this problem. 

According to my experience, Moodle does not simply show a blank page. A blank page appears if the page build process fails really early and fatally and showing PHP debug messages in the browser is fully disabled.

Didn't you really get _any_ debug messages during the Moodle upgrade process and / or can you please check your PHP log if there are any debug messages? 

If you can give us a debug message which is related to this fatal error, we can check it to see if Boost Union is really the culprit or if any other plugin caused the page failure and it was just a coincidence that removing Boost Union solved the problem in the second run.

Cheers,
Alex

**Comment by caiadogithub** [comment]
Hi, Alex.

Thanks fro the reply.

Cache clear => Problem gone!

Ricardo
