### ISSUE TITLE
Bug: H5P Content triggers error message

### ISSUE THREAD

**Issue by LehnS** [moodle-an-hochschulen/moodle-theme_boost_union#79]
Hi,
to show the content of H5P activities in the course directly, I used a label and the H5P button in the atto text editor. 
After saving the content wasn't shown, instead I got the following error message (firefox & chrome):

<img width="1086" alt="firefox" src="https://user-images.githubusercontent.com/113052383/189473492-488802fc-12ae-4e87-af1e-2d34ea37a768.png">

<img width="1348" alt="chrome" src="https://user-images.githubusercontent.com/113052383/189473506-6b040f6a-bd64-46c2-83c3-99301ab554f3.png">

 When I switched the theme back to boost it worked fine. We are using Moodle 4.0.3 (Build: 20220822).
 
 Best regards,
 Sandra

**Comment by abias** [comment]
Hi Sandra,

thanks for reporting this issue.

I tried to reproduce it on the latest codebase (Boost Union v4.0-r2 and Moodle 4.0.4+), but unfortunately / luckily I was able to add a H5P content element within a label activity without problems.

May I ask you to test again on the same / latest codebase to see if the issue has magically disappeared? 
If it did not, please provide detailed steps to reproduce which especially include the information a) when exactly the error appeared, b) what you did before that and c) which H5P content element type you were adding.

Cheers,
Alex

**Comment by abias** [comment]
Hi Sandra,

as you didn't reply anymore, I dare to close this issue for now.
Don't hesitate to come back to us if you can reproduce the issue again.

Cheers,
Alex
