### ISSUE TITLE
Feature: Allow admins to customize the course navigation (course index)

### ISSUE THREAD

**Issue by abias** [moodle-an-hochschulen/moodle-theme_boost_union#8]
Moodle 4.x radically changed the way how users navigate in courses.
However, most of the new navigation processes in Moodle 4.x are hardcoded (again, as they were before in Moodle 3.x).

Some admin might want to be able to customize the course navigation in some aspects.

This issue is a place to discuss the needs and to identify real pain points which could then be solved afterwards.
This issue also has a large overlap with the thoughts what https://moodle.org/plugins/local_boostnavigation does and should be doing on Moodle 4.x

**Comment by christianwolters** [comment]
Hey Alex,

just to clarify: the scope of this issue is the course - section - navigation in the left (nav-)drawer, right?

If this is the case: I'll create a seperate issue for the course settings, okay?

**Comment by lucaboesch** [comment]
It's not called nav drawer any more, but has become the 'course index'.

**Comment by wiebkemueller-hsh** [comment]
If this becomes part of the theme we would suggest to keep an eye on the admin settings in local_boostnavigation and to think about an option that lets admins define which term should be opened by default (current term, latest term that has been set, no term).

It might be easier to keep it in a seperate plugin but then let the theme decide where users can access the menu.

**Comment by dbnschools** [comment]
Just a suggestion of a possible improvement might be to make any topic which is highlighted appear at the top of the course index below the topic 0.  I think this would help eliminate some scrolling.  

Another interesting thought would be to put all the links in the secondary menu into a drop down section in the course index.  This would truly streamline where people look for navigation and everything within a course would be in the sidebar with just content in the main area.  

This is a substantial UX change as it would eliminate one area of navigation that was prominent and obvious to the user.  On the other hand, it puts all navigation for a course in one area and allows the main area to be just content.

**Comment by wiebkemueller-hsh** [comment]
Our users complain about the following regarding the course index:

-  frequently the section titles in the course index are cut off, they had the idea to adjust the index width manually, maybe also let the section titles break 
-  when scrolling down the course content, there is no way to identify which course you're in, this could be solved by writing the course title (long,short) in the course index
