### ISSUE TITLE
Duplicated title when viewing activities

### ISSUE THREAD

**Issue by yanus** [moodle-an-hochschulen/moodle-theme_boost_union#82]
When viewing an activity (e.g. forum, page, SCORM package), the title is shown twice, once in the page header and then again in the page content. To illustrate, below are two screenshots, first with Boost Union and second with regular Boost.

![image](https://user-images.githubusercontent.com/5475686/190357504-6031b52f-49e3-4389-bdbf-31b9d87bf29a.png)
![image](https://user-images.githubusercontent.com/5475686/190357581-6b29cbc7-759e-44a4-91d9-2b49a71ac38a.png)

**Comment by christianwolters** [comment]
Hi @yanus,

thank  you for reporting this. I was seeing this to, but thought I was messing something up and forgot about it.

Cheers 
Christian

**Comment by lucaboesch** [comment]
I could reproduce this, @yanus as well.
Additionally, I might add, that there's the activity navigation kicking in, too.
A UI element which otherwise would have been ditched from Moodle 4.0.
That creates a inconsistency, which is bad.

Best,
Luca

**Comment by abias** [comment]
Hi @yanus , 

thanks for reporting this issue. This was a glitch in my work which was just solved by Luca in #87.

Cheers,
Alex
