### ISSUE TITLE
Improvement: Fallback CSS file leads to Code prechecker error

### ISSUE THREAD

**Issue by lucaboesch** [moodle-an-hochschulen/moodle-theme_boost_union#91]
In a line (line 13866) of the newly introduced moodle.css fallback file a Code prechecker CSS error "" is triggered due to a wrongly placed /* stylelint-disable-line declaration-no-important */.

**Comment by lucaboesch** [comment]
You are abslutely right @abias and my comment in the pull request points into the same direction noting that my proposed fix isn't the right move to amend.
I omitted why, but you pointed out the reasoning behind this very well.

**Comment by abias** [comment]
With the change which I just mentioned in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/89#issuecomment-1384546299, this issue should be solved for now.
