### ISSUE TITLE
Feature: Filter courses in navigation panel

### ISSUE THREAD

**Issue by KaiGitGub** [moodle-an-hochschulen/moodle-theme_boost_union#93]
Hi,
in your plugin boost navitgation for moodle 3.X there was an option to filter courses (all, upcoming, old etc) in the navigation panel.
Would be great to see it also in this theme, because it only shows all courses (and it might be plenty of them).

**Comment by abias** [comment]
I think this issue can be considered as solved as #300 which provides dynamic course lists has been merged now.
