### ISSUE TITLE
4.0 r2 version deleted administration and navigation in blocks

### ISSUE THREAD

**Issue by KaiGitGub** [moodle-an-hochschulen/moodle-theme_boost_union#96]
after update'ing theme to 4.0 r2 version the navigation panel and administration disappeared from block panels (right site menu).

recreate the problem: update the theme

**Comment by lucaboesch** [comment]
Dear @KaiGitGub that's not a bug, it's a feature!
Boost Theme do not work with the navigation and administration block.
That was issue #67.

Best, Luca

**Comment by KaiGitGub** [comment]
ach okay, it worked in 4.0 r1 :)
